In [1]:
import numpy as np
import pandas as pd

In [2]:
ep = pd.read_csv('data/employees.csv')
ep

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male     8/6/93       NaN   True     Marketing
1        Thomas    Male    3/31/96   61933.0   True           NaN
2         Maria  Female        NaN  130590.0  False       Finance
3         Jerry     NaN     3/4/05  138705.0   True       Finance
4         Larry    Male    1/24/98  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male    1/31/84   42392.0  False       Finance
997     Russell    Male    5/20/13   96914.0  False       Product
998       Larry    Male    4/20/13   60500.0  False  Business Dev
999      Albert    Male    5/15/12  129949.0   True         Sales
1000        NaN     NaN        NaN       NaN    NaN           NaN

[1001 rows x 6 columns]

In [3]:
ep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    object
 3   Salary      999 non-null    float64
 4   Mgmt        933 non-null    object
 5   Team        957 non-null    object
dtypes: float64(1), object(5)
memory usage: 47.1+ KB

## 1) Optimize dtype and columns

In [10]:
ep = pd.read_csv('data/employees.csv',parse_dates=['Start Date'],date_format="%m/%d/%y")
ep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        933 non-null    object
 5   Team        957 non-null    object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 47.1+ KB

In [13]:
ep['Mgmt'] = ep['Mgmt'].astype(bool) # Nan --- > True
ep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(1), object(3)
memory usage: 40.2+ KB

In [15]:
ep['Salary'] = ep['Salary'].fillna(0).astype('int32')
ep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int32
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), int32(1), object(3)
memory usage: 36.3+ KB

In [16]:
ep.nunique()

First Name    200
Gender          2
Start Date    971
Salary        995
Mgmt            2
Team           10
dtype: int64

In [17]:
ep['Gender'] = ep['Gender'].astype('category')
ep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int32
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), category(1), datetime64[ns](1), int32(1), object(2)
memory usage: 29.6+ KB

In [18]:
ep['Team'] = ep['Team'].astype('category')
ep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int32
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    category
dtypes: bool(1), category(2), datetime64[ns](1), int32(1), object(1)
memory usage: 23.1+ KB

## 2) Use Some Columns

In [20]:
ep = pd.read_csv('data/employees.csv',parse_dates=['Start Date'],date_format="%m/%d/%y",usecols=['Start Date','Gender','Salary','Mgmt','Team'])
ep

      Gender Start Date    Salary   Mgmt          Team
0       Male 1993-08-06       NaN   True     Marketing
1       Male 1996-03-31   61933.0   True           NaN
2     Female        NaT  130590.0  False       Finance
3        NaN 2005-03-04  138705.0   True       Finance
4       Male 1998-01-24  101004.0   True            IT
...      ...        ...       ...    ...           ...
996     Male 1984-01-31   42392.0  False       Finance
997     Male 2013-05-20   96914.0  False       Product
998     Male 2013-04-20   60500.0  False  Business Dev
999     Male 2012-05-15  129949.0   True         Sales
1000     NaN        NaT       NaN    NaN           NaN

[1001 rows x 5 columns]

In [21]:
ep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      854 non-null    object
 1   Start Date  999 non-null    datetime64[ns]
 2   Salary      999 non-null    float64
 3   Mgmt        933 non-null    object
 4   Team        957 non-null    object
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 39.2+ KB

In [22]:
ep['Mgmt'] = ep['Mgmt'].astype(bool) # Nan --- > True
ep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      854 non-null    object
 1   Start Date  999 non-null    datetime64[ns]
 2   Salary      999 non-null    float64
 3   Mgmt        1001 non-null   bool
 4   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(1), object(2)
memory usage: 32.4+ KB

In [23]:
ep['Salary'] = ep['Salary'].fillna(0).astype('int32')
ep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      854 non-null    object
 1   Start Date  999 non-null    datetime64[ns]
 2   Salary      1001 non-null   int32
 3   Mgmt        1001 non-null   bool
 4   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), int32(1), object(2)
memory usage: 28.5+ KB

In [24]:
ep.nunique()

Gender          2
Start Date    971
Salary        995
Mgmt            2
Team           10
dtype: int64

In [25]:
ep['Gender'] = ep['Gender'].astype('category')
ep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      854 non-null    category
 1   Start Date  999 non-null    datetime64[ns]
 2   Salary      1001 non-null   int32
 3   Mgmt        1001 non-null   bool
 4   Team        957 non-null    object
dtypes: bool(1), category(1), datetime64[ns](1), int32(1), object(1)
memory usage: 21.8+ KB

In [26]:
ep['Team'] = ep['Team'].astype('category')
ep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      854 non-null    category
 1   Start Date  999 non-null    datetime64[ns]
 2   Salary      1001 non-null   int32
 3   Mgmt        1001 non-null   bool
 4   Team        957 non-null    category
dtypes: bool(1), category(2), datetime64[ns](1), int32(1)
memory usage: 15.3 KB

## 3) Dtype Read-Csv

In [30]:
ep = pd.read_csv('data/employees.csv',parse_dates=['Start Date'],date_format="%m/%d/%y",usecols=['Start Date','Gender','Salary','Mgmt','Team'],dtype={'Gender':'category','salary':'int32'})
ep

      Gender Start Date    Salary   Mgmt          Team
0       Male 1993-08-06       NaN   True     Marketing
1       Male 1996-03-31   61933.0   True           NaN
2     Female        NaT  130590.0  False       Finance
3        NaN 2005-03-04  138705.0   True       Finance
4       Male 1998-01-24  101004.0   True            IT
...      ...        ...       ...    ...           ...
996     Male 1984-01-31   42392.0  False       Finance
997     Male 2013-05-20   96914.0  False       Product
998     Male 2013-04-20   60500.0  False  Business Dev
999     Male 2012-05-15  129949.0   True         Sales
1000     NaN        NaT       NaN    NaN           NaN

[1001 rows x 5 columns]

In [31]:
ep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      854 non-null    category
 1   Start Date  999 non-null    datetime64[ns]
 2   Salary      999 non-null    float64
 3   Mgmt        933 non-null    object
 4   Team        957 non-null    object
dtypes: category(1), datetime64[ns](1), float64(1), object(2)
memory usage: 32.5+ KB

## 4) Chunk Size

In [32]:
for ep in pd.read_csv('data/employees.csv',parse_dates=['Start Date'],date_format="%m/%d/%y",chunksize=200):
    ep.info()
    print(">>>>>>>>>>>>>>>>>>>>>>>>>>>")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  185 non-null    object
 1   Gender      168 non-null    object
 2   Start Date  199 non-null    datetime64[ns]
 3   Salary      199 non-null    float64
 4   Mgmt        185 non-null    object
 5   Team        192 non-null    object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 9.5+ KB
>>>>>>>>>>>>>>>>>>>>>>>>>>>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 200 to 399
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  187 non-null    object
 1   Gender      172 non-null    object
 2   Start Date  200 non-null    datetime64[ns]
 3   Salary      200 non-null    int64
 4   Mgmt        187 non-null    object
 5   Team        195 non-null    object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 9.5+ KB
>>>>>>>>>>>>>>>>>>>>>>>>>>>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 400 to 599
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  188 non-null    object
 1   Gender      177 non-null    object
 2   Start Date  200 non-null    datetime64[ns]
 3   Salary      200 non-null    int64
 4   Mgmt        188 non-null    object
 5   Team        190 non-null    object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 9.5+ KB
>>>>>>>>>>>>>>>>>>>>>>>>>>>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 600 to 799
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  184 non-null    object
 1   Gender      162 non-null    object
 2   Start Date  200 non-null    datetime64[ns]
 3   Salary      200 non-null    int64
 4   Mgmt        184 non-null    object
 5   Team        188 non-null    object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 9.5+ KB
>>>>>>>>>>>>>>>>>>>>>>>>>>>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 800 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  189 non-null    object
 1   Gender      175 non-null    object
 2   Start Date  200 non-null    datetime64[ns]
 3   Salary      200 non-null    int64
 4   Mgmt        189 non-null    object
 5   Team        192 non-null    object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 9.5+ KB
>>>>>>>>>>>>>>>>>>>>>>>>>>>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 1000 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  0 non-null      float64
 1   Gender      0 non-null      float64
 2   Start Date  0 non-null      datetime64[ns]
 3   Salary      0 non-null      float64
 4   Mgmt        0 non-null      float64
 5   Team        0 non-null      float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 180.0 bytes
>>>>>>>>>>>>>>>>>>>>>>>>>>>