In [2]:
import pandas as pd
import numpy as np

In [6]:
ep = pd.read_csv('data/employees.csv', parse_dates=['Start Date'], date_format="%m/%d/%y")
ep

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
2         Maria  Female        NaT  130590.0  False       Finance
3         Jerry     NaN 2005-03-04  138705.0   True       Finance
4         Larry    Male 1998-01-24  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN    NaN           NaN

[1001 rows x 6 columns]

In [9]:
ep['First Name'] == 'Maria'

0       False
1       False
2        True
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000    False
Name: First Name, Length: 1001, dtype: bool

In [10]:
ep[ep['First Name'] == 'Maria']

    First Name  Gender Start Date    Salary   Mgmt          Team
2        Maria  Female        NaT  130590.0  False       Finance
198      Maria  Female 1990-12-27   36067.0   True       Product
815      Maria     NaN 1986-01-18  106562.0  False            HR
844      Maria     NaN 1985-06-19  148857.0  False         Legal
936      Maria  Female 2003-03-14   96250.0  False  Business Dev
984      Maria  Female 2011-10-15   43455.0  False   Engineering

In [11]:
ep[ep['Team']!='Finance']

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
4         Larry    Male 1998-01-24  101004.0   True            IT
5        Dennis    Male 1987-04-18  115163.0  False         Legal
6          Ruby  Female 1987-08-17   65476.0   True       Product
...         ...     ...        ...       ...    ...           ...
995       Henry     NaN 2014-11-23  132483.0  False  Distribution
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN    NaN           NaN

[899 rows x 6 columns]

In [13]:
ep['Mgmt'] = ep['Mgmt'].astype(bool)
ep[ep['Mgmt']]

     First Name  Gender Start Date    Salary  Mgmt         Team
0       Douglas    Male 1993-08-06       NaN  True    Marketing
1        Thomas    Male 1996-03-31   61933.0  True          NaN
3         Jerry     NaN 2005-03-04  138705.0  True      Finance
4         Larry    Male 1998-01-24  101004.0  True           IT
6          Ruby  Female 1987-08-17   65476.0  True      Product
...         ...     ...        ...       ...   ...          ...
992     Anthony    Male 2011-10-16  112769.0  True      Finance
993        Tina  Female 1997-05-15   56450.0  True  Engineering
994      George    Male 2013-06-21   98874.0  True    Marketing
999      Albert    Male 2012-05-15  129949.0  True        Sales
1000        NaN     NaN        NaT       NaN  True          NaN

[536 rows x 6 columns]

In [14]:
high_salary = ep['Salary']>100000
ep[high_salary]

    First Name  Gender Start Date    Salary   Mgmt          Team
2        Maria  Female        NaT  130590.0  False       Finance
3        Jerry     NaN 2005-03-04  138705.0   True       Finance
4        Larry    Male 1998-01-24  101004.0   True            IT
5       Dennis    Male 1987-04-18  115163.0  False         Legal
9      Frances  Female 2002-08-08  139852.0   True  Business Dev
..         ...     ...        ...       ...    ...           ...
990      Robin  Female 1987-07-24  100765.0   True            IT
991       Rose  Female 2002-08-25  134505.0   True     Marketing
992    Anthony    Male 2011-10-16  112769.0   True       Finance
995      Henry     NaN 2014-11-23  132483.0  False  Distribution
999     Albert    Male 2012-05-15  129949.0   True         Sales

[409 rows x 6 columns]

In [15]:
is_female = ep['Gender']=='Female'
is_fin = ep['Team']=='Finance'

In [16]:
ep[is_female & is_fin] # and

    First Name  Gender Start Date    Salary   Mgmt     Team
2        Maria  Female        NaT  130590.0  False  Finance
7          NaN  Female 2015-07-20   45906.0   True  Finance
14    Kimberly  Female 1999-01-14   41426.0   True  Finance
67      Rachel  Female 1999-08-16   51178.0   True  Finance
84       Doris  Female 2004-08-20   83072.0  False  Finance
96     Cynthia  Female 1994-03-21  142321.0  False  Finance
100    Melissa  Female 2005-06-21   48109.0  False  Finance
103    Phyllis  Female 1996-10-11  136984.0   True  Finance
105      Kathy  Female 1996-03-09   91712.0  False  Finance
142  Elizabeth  Female 2003-10-09  146129.0  False  Finance
160      Kathy  Female 2000-03-18  149563.0   True  Finance
172       Sara  Female 1991-09-23   97058.0  False  Finance
179    Jessica  Female 1995-10-23   68759.0   True  Finance
190      Carol  Female 1996-03-19   57783.0  False  Finance
226      Kathy  Female 1995-04-19   50905.0   True  Finance
268      Irene  Female 1982-03-03   56526.0   True  Finance
276  Christine  Female 1989-07-03   94345.0  False  Finance
399    Kathryn  Female 1988-06-09   86439.0  False  Finance
405     Sharon  Female 2014-03-09   91522.0  False  Finance
418      Julia  Female 1982-03-02   36403.0   True  Finance
425      Alice  Female 1986-05-02   51395.0   True  Finance
436    Kathryn  Female 2007-08-29   53061.0   True  Finance
442      Julie  Female 1998-04-23   73437.0   True  Finance
485     Ashley  Female 1997-08-15  142415.0   True  Finance
526    Barbara  Female 2004-03-22  144677.0  False  Finance
540        NaN  Female 2009-12-02   84746.0   True  Finance
547     Evelyn  Female 1998-09-22   51525.0  False  Finance
549       Sara  Female 1980-02-25   75484.0  False  Finance
595      Nancy  Female 1985-05-07  121006.0   True  Finance
644  Katherine  Female 1996-08-13  149908.0  False  Finance
646  Elizabeth  Female 2010-02-21   79145.0  False  Finance
649       Ruth  Female 2004-02-17   59969.0   True  Finance
650    Cynthia  Female 1986-07-05   35381.0  False  Finance
691       Joan  Female 2007-10-02  120941.0   True  Finance
702      Debra  Female 2011-03-17   84693.0   True  Finance
731        Ann  Female 2001-07-16  118431.0   True  Finance
775       Rose  Female 1999-11-03   75181.0   True  Finance
807       Mary  Female 2011-11-06  115057.0  False  Finance
836    Carolyn  Female 2004-03-17  118037.0  False  Finance
884       Lisa  Female 2003-10-17   73706.0  False  Finance
889   Margaret  Female 2001-01-04  126924.0   True  Finance
905      Alice  Female 2013-02-09  121250.0   True  Finance
907  Elizabeth  Female 1998-07-27  137144.0  False  Finance
987     Gloria  Female 2014-12-08  136709.0   True  Finance

In [17]:
ep[is_female | is_fin] # or

    First Name  Gender Start Date    Salary   Mgmt         Team
2        Maria  Female        NaT  130590.0  False      Finance
3        Jerry     NaN 2005-03-04  138705.0   True      Finance
6         Ruby  Female 1987-08-17   65476.0   True      Product
7          NaN  Female 2015-07-20   45906.0   True      Finance
8       Angela  Female 2005-11-22   95570.0   True  Engineering
..         ...     ...        ...       ...    ...          ...
990      Robin  Female 1987-07-24  100765.0   True           IT
991       Rose  Female 2002-08-25  134505.0   True    Marketing
992    Anthony    Male 2011-10-16  112769.0   True      Finance
993       Tina  Female 1997-05-15   56450.0   True  Engineering
996    Phillip    Male 1984-01-31   42392.0  False      Finance

[489 rows x 6 columns]

In [18]:
ep[is_female ^ is_fin] # xor

    First Name  Gender Start Date    Salary   Mgmt          Team
3        Jerry     NaN 2005-03-04  138705.0   True       Finance
6         Ruby  Female 1987-08-17   65476.0   True       Product
8       Angela  Female 2005-11-22   95570.0   True   Engineering
9      Frances  Female 2002-08-08  139852.0   True  Business Dev
10      Louise  Female 1980-08-12   63241.0   True           NaN
..         ...     ...        ...       ...    ...           ...
990      Robin  Female 1987-07-24  100765.0   True            IT
991       Rose  Female 2002-08-25  134505.0   True     Marketing
992    Anthony    Male 2011-10-16  112769.0   True       Finance
993       Tina  Female 1997-05-15   56450.0   True   Engineering
996    Phillip    Male 1984-01-31   42392.0  False       Finance

[445 rows x 6 columns]

In [21]:
is_female

0       False
1       False
2        True
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000    False
Name: Gender, Length: 1001, dtype: bool

In [22]:
~is_female

0        True
1        True
2       False
3        True
4        True
        ...
996      True
997      True
998      True
999      True
1000     True
Name: Gender, Length: 1001, dtype: bool

In [19]:
ep[~is_female & is_fin] # xor

      First Name Gender Start Date    Salary   Mgmt     Team
3          Jerry    NaN 2005-03-04  138705.0   True  Finance
46         Bruce   Male 2009-11-28  114796.0  False  Finance
53          Alan    NaN 2014-03-03   40341.0   True  Finance
56          Carl   Male 2006-05-03  130276.0   True  Finance
68          Jose   Male 2004-10-30   84834.0   True  Finance
69         Irene    NaN 2015-07-14  100863.0   True  Finance
83         Shawn   Male 2005-09-23  148115.0   True  Finance
117       Steven   Male 1995-03-01  109095.0  False  Finance
153       Victor    NaN 2011-03-10   84546.0   True  Finance
200         Gary   Male 1987-08-12   89661.0  False  Finance
205      Brandon   Male 2006-03-27  115711.0   True  Finance
218      Gregory    NaN 1992-06-15   98865.0   True  Finance
219        Billy   Male 1995-03-13  120444.0   True  Finance
222        Jason   Male 1999-10-17   78417.0  False  Finance
241       Walter   Male 1983-07-06  127813.0  False  Finance
286         Todd   Male 1984-02-02   69989.0   True  Finance
304       Jeremy   Male 1981-08-12   46930.0   True  Finance
311       Ernest    NaN 2002-01-18   72145.0   True  Finance
318          Roy   Male 2006-08-06  148225.0  False  Finance
328       Samuel   Male 1991-12-19   76076.0   True  Finance
335       Robert   Male 2014-11-18   85799.0  False  Finance
341       Carlos   Male 2007-09-19   77327.0   True  Finance
348       Philip   Male 1989-08-02  129968.0  False  Finance
363       Justin    NaN 2005-04-15   96978.0  False  Finance
415      Shirley    NaN 1990-11-16   67811.0  False  Finance
420       Justin   Male 1986-05-22  121508.0   True  Finance
428  Christopher   Male 1999-05-13   68028.0   True  Finance
458       Albert   Male 2007-09-30  102626.0  False  Finance
493        Craig   Male 2005-11-01   44857.0  False  Finance
582        Harry   Male 1982-11-19   59277.0  False  Finance
613       Teresa    NaN 1992-01-03   63103.0  False  Finance
618        Peter   Male 1992-11-24   69297.0  False  Finance
620        Ralph   Male 2012-03-07   81215.0  False  Finance
642       Amanda    NaN 2010-03-16  135118.0  False  Finance
685          NaN   Male 1989-10-20   88086.0   True  Finance
686         Paul    NaN 2011-02-18   91462.0  False  Finance
689        Julie    NaN 1980-05-08   50529.0  False  Finance
710       Edward   Male 1997-11-27   58327.0   True  Finance
725       Jeremy   Male 1991-05-19  131513.0   True  Finance
732        Henry   Male 1986-05-12   59943.0  False  Finance
744         Judy    NaN 2011-07-15   46829.0   True  Finance
765        Alice    NaN 1995-04-23  148339.0   True  Finance
773          NaN   Male 1986-10-24   47176.0   True  Finance
790         Fred   Male 1989-03-03  129712.0  False  Finance
809       George   Male 1995-09-27   36749.0  False  Finance
831      Kenneth   Male 2015-01-15   69112.0   True  Finance
837       Joseph   Male 1985-05-23  139570.0   True  Finance
847       Nicole    NaN 1981-05-02   41449.0  False  Finance
854        Harry   Male 1985-02-10   63046.0  False  Finance
856       Bonnie    NaN 2006-01-18  108946.0  False  Finance
861        Jerry   Male 1989-03-26  140850.0  False  Finance
880       Robert    NaN 2007-05-25   90998.0  False  Finance
890          NaN   Male 2015-11-24  145329.0   True  Finance
891      Timothy   Male 1991-08-25   92587.0  False  Finance
897      Kenneth    NaN 1994-02-28   95296.0  False  Finance
954          Joe   Male 1980-01-19  119667.0   True  Finance
992      Anthony   Male 2011-10-16  112769.0   True  Finance
996      Phillip   Male 1984-01-31   42392.0  False  Finance

In [23]:
ep[ep['Team'].eq('Finance')]   ## ep[ep["Team"]=='Finance']

    First Name  Gender Start Date    Salary   Mgmt     Team
2        Maria  Female        NaT  130590.0  False  Finance
3        Jerry     NaN 2005-03-04  138705.0   True  Finance
7          NaN  Female 2015-07-20   45906.0   True  Finance
14    Kimberly  Female 1999-01-14   41426.0   True  Finance
46       Bruce    Male 2009-11-28  114796.0  False  Finance
..         ...     ...        ...       ...    ...      ...
907  Elizabeth  Female 1998-07-27  137144.0  False  Finance
954        Joe    Male 1980-01-19  119667.0   True  Finance
987     Gloria  Female 2014-12-08  136709.0   True  Finance
992    Anthony    Male 2011-10-16  112769.0   True  Finance
996    Phillip    Male 1984-01-31   42392.0  False  Finance

[102 rows x 6 columns]

In [26]:
ep[ep['Team'].ne('Finance')]   ## ep[ep["Team"]!='Finance']

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
4         Larry    Male 1998-01-24  101004.0   True            IT
5        Dennis    Male 1987-04-18  115163.0  False         Legal
6          Ruby  Female 1987-08-17   65476.0   True       Product
...         ...     ...        ...       ...    ...           ...
995       Henry     NaN 2014-11-23  132483.0  False  Distribution
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN   True           NaN

[899 rows x 6 columns]

In [27]:
ep[ep['Salary'].gt(100000)]   ## ep[ep["Salary"]>100000]

    First Name  Gender Start Date    Salary   Mgmt          Team
2        Maria  Female        NaT  130590.0  False       Finance
3        Jerry     NaN 2005-03-04  138705.0   True       Finance
4        Larry    Male 1998-01-24  101004.0   True            IT
5       Dennis    Male 1987-04-18  115163.0  False         Legal
9      Frances  Female 2002-08-08  139852.0   True  Business Dev
..         ...     ...        ...       ...    ...           ...
990      Robin  Female 1987-07-24  100765.0   True            IT
991       Rose  Female 2002-08-25  134505.0   True     Marketing
992    Anthony    Male 2011-10-16  112769.0   True       Finance
995      Henry     NaN 2014-11-23  132483.0  False  Distribution
999     Albert    Male 2012-05-15  129949.0   True         Sales

[409 rows x 6 columns]

In [28]:
ep[ep['Salary'].ge(100000)]   ## ep[ep["Salary"]>=100000]

    First Name  Gender Start Date    Salary   Mgmt          Team
2        Maria  Female        NaT  130590.0  False       Finance
3        Jerry     NaN 2005-03-04  138705.0   True       Finance
4        Larry    Male 1998-01-24  101004.0   True            IT
5       Dennis    Male 1987-04-18  115163.0  False         Legal
9      Frances  Female 2002-08-08  139852.0   True  Business Dev
..         ...     ...        ...       ...    ...           ...
990      Robin  Female 1987-07-24  100765.0   True            IT
991       Rose  Female 2002-08-25  134505.0   True     Marketing
992    Anthony    Male 2011-10-16  112769.0   True       Finance
995      Henry     NaN 2014-11-23  132483.0  False  Distribution
999     Albert    Male 2012-05-15  129949.0   True         Sales

[409 rows x 6 columns]

In [29]:
ep[ep['Salary'].lt(100000)]   ## ep[ep["Salary"]<100000]

    First Name  Gender Start Date   Salary   Mgmt          Team
1       Thomas    Male 1996-03-31  61933.0   True           NaN
6         Ruby  Female 1987-08-17  65476.0   True       Product
7          NaN  Female 2015-07-20  45906.0   True       Finance
8       Angela  Female 2005-11-22  95570.0   True   Engineering
10      Louise  Female 1980-08-12  63241.0   True           NaN
..         ...     ...        ...      ...    ...           ...
993       Tina  Female 1997-05-15  56450.0   True   Engineering
994     George    Male 2013-06-21  98874.0   True     Marketing
996    Phillip    Male 1984-01-31  42392.0  False       Finance
997    Russell    Male 2013-05-20  96914.0  False       Product
998      Larry    Male 2013-04-20  60500.0  False  Business Dev

[590 rows x 6 columns]

In [30]:
ep[ep['Salary'].le(100000)]   ## ep[ep["Salary"]<=100000]

    First Name  Gender Start Date   Salary   Mgmt          Team
1       Thomas    Male 1996-03-31  61933.0   True           NaN
6         Ruby  Female 1987-08-17  65476.0   True       Product
7          NaN  Female 2015-07-20  45906.0   True       Finance
8       Angela  Female 2005-11-22  95570.0   True   Engineering
10      Louise  Female 1980-08-12  63241.0   True           NaN
..         ...     ...        ...      ...    ...           ...
993       Tina  Female 1997-05-15  56450.0   True   Engineering
994     George    Male 2013-06-21  98874.0   True     Marketing
996    Phillip    Male 1984-01-31  42392.0  False       Finance
997    Russell    Male 2013-05-20  96914.0  False       Product
998      Larry    Male 2013-04-20  60500.0  False  Business Dev

[590 rows x 6 columns]

In [31]:
ep["Team"].isin(['Finance','Engineering','Product'])

0       False
1       False
2        True
3        True
4       False
        ...
996      True
997      True
998     False
999     False
1000    False
Name: Team, Length: 1001, dtype: bool

In [33]:
ep[ep["Team"].isin(['Finance','Engineering','Product'])]

    First Name  Gender Start Date    Salary   Mgmt         Team
2        Maria  Female        NaT  130590.0  False      Finance
3        Jerry     NaN 2005-03-04  138705.0   True      Finance
6         Ruby  Female 1987-08-17   65476.0   True      Product
7          NaN  Female 2015-07-20   45906.0   True      Finance
8       Angela  Female 2005-11-22   95570.0   True  Engineering
..         ...     ...        ...       ...    ...          ...
987     Gloria  Female 2014-12-08  136709.0   True      Finance
992    Anthony    Male 2011-10-16  112769.0   True      Finance
993       Tina  Female 1997-05-15   56450.0   True  Engineering
996    Phillip    Male 1984-01-31   42392.0  False      Finance
997    Russell    Male 2013-05-20   96914.0  False      Product

[289 rows x 6 columns]

In [34]:
ep[ep['Salary'].between(80000,90000)]

    First Name  Gender Start Date   Salary   Mgmt         Team
19       Donna  Female 2010-07-22  81014.0  False      Product
31       Joyce     NaN 2005-02-20  88657.0  False      Product
35     Theresa  Female 2006-10-10  85182.0  False        Sales
45       Roger    Male 1980-04-17  88010.0   True        Sales
54        Sara  Female 2007-08-15  83677.0  False  Engineering
..         ...     ...        ...      ...    ...          ...
930      Nancy  Female 2001-09-10  85213.0   True    Marketing
956    Beverly  Female 1986-10-17  80838.0  False  Engineering
963        Ann  Female 1994-09-23  89443.0   True        Sales
985    Stephen     NaN 1983-07-10  85668.0  False        Legal
986      Donna  Female 1982-11-26  82871.0  False    Marketing

[94 rows x 6 columns]

In [35]:
ep[ep['Start Date'].between('1980-01-01','1990-01-01')]

    First Name  Gender Start Date    Salary   Mgmt         Team
5       Dennis    Male 1987-04-18  115163.0  False        Legal
6         Ruby  Female 1987-08-17   65476.0   True      Product
10      Louise  Female 1980-08-12   63241.0   True          NaN
12     Brandon    Male 1980-12-01  112807.0   True           HR
17       Shawn    Male 1986-12-07  111737.0  False      Product
..         ...     ...        ...       ...    ...          ...
983       John    Male 1982-12-23  146907.0  False  Engineering
985    Stephen     NaN 1983-07-10   85668.0  False        Legal
986      Donna  Female 1982-11-26   82871.0  False    Marketing
990      Robin  Female 1987-07-24  100765.0   True           IT
996    Phillip    Male 1984-01-31   42392.0  False      Finance

[240 rows x 6 columns]

In [38]:
ep[ep['First Name'].between('W','z')]

    First Name  Gender Start Date    Salary   Mgmt          Team
112     Willie    Male 2003-11-27   64363.0  False     Marketing
127    William    Male 2002-09-29   66521.0  False            HR
175     Willie    Male 1998-02-17  146651.0   True   Engineering
177      Wayne    Male 2012-04-07  102652.0   True  Distribution
204     Willie    Male 2006-06-06   55281.0   True     Marketing
241     Walter    Male 1983-07-06  127813.0  False       Finance
288     Walter     NaN 1999-12-21   66757.0  False  Distribution
433      Wanda  Female 2008-07-20   65362.0   True         Legal
448      Wayne    Male 1992-01-30   81183.0  False            IT
450     Willie    Male 2009-08-22   55038.0  False         Legal
466     Walter    Male 2007-08-04   58789.0  False         Sales
512      Wanda  Female 1993-04-06   78883.0  False           NaN
637      Wayne    Male 2009-09-02  126956.0  False            HR
652     Willie    Male 2009-12-05  141932.0   True   Engineering
655     Walter    Male 2007-09-24  125382.0   True            IT
820    William    Male 1993-11-18   54058.0   True            HR
899     Walter    Male 1992-05-21  144701.0   True     Marketing
941    William    Male 1997-06-26  104840.0   True   Engineering
943      Wayne    Male 2006-09-08   67471.0  False   Engineering

In [40]:
ep[ep['Team'].isnull()]

       First Name  Gender Start Date    Salary   Mgmt Team
1          Thomas    Male 1996-03-31   61933.0   True  NaN
10         Louise  Female 1980-08-12   63241.0   True  NaN
23            NaN    Male 2012-06-14  125792.0   True  NaN
32            NaN    Male 1998-08-21  122340.0   True  NaN
91          James     NaN 2005-01-26  128771.0  False  NaN
109   Christopher    Male 2000-04-22   37919.0  False  NaN
139           NaN  Female 1990-10-03  132373.0   True  NaN
199      Jonathan    Male 2009-07-17  130581.0   True  NaN
258       Michael    Male 2002-01-24   43586.0  False  NaN
290        Jeremy    Male 1988-06-14  129460.0   True  NaN
314         Bobby    Male 1996-03-31  112117.0  False  NaN
367        Edward    Male 1989-08-04   66067.0   True  NaN
382           NaN  Female 1996-04-18  107024.0   True  NaN
434         Joyce  Female 1995-02-07   50701.0   True  NaN
438         Jason    Male 1998-11-20   69244.0   True  NaN
445         Chris    Male 2006-12-12   71642.0  False  NaN
479       Richard    Male 1997-07-04   47647.0   True  NaN
512         Wanda  Female 1993-04-06   78883.0  False  NaN
513         Jimmy    Male 2013-11-19   63549.0  False  NaN
520         Peter    Male 2003-02-22   56580.0   True  NaN
567           NaN  Female 1980-04-01   48141.0   True  NaN
573      Kimberly  Female 1981-12-30   81800.0   True  NaN
580         Harry    Male 1985-01-27   65482.0  False  NaN
626           NaN  Female 1997-04-13  131755.0   True  NaN
634          Carl    Male 1987-03-30   75598.0  False  NaN
635         Randy    Male 2000-09-27   89831.0   True  NaN
647        Donald    Male 1988-04-06  122920.0  False  NaN
669        Joseph     NaN 1982-03-28   86564.0   True  NaN
684         Alice  Female 2016-01-21  117787.0  False  NaN
706          Todd    Male 1993-07-04  128175.0   True  NaN
726        Daniel    Male 2016-02-29   77287.0   True  NaN
753       Antonio    Male 1999-06-06   41928.0   True  NaN
774           NaN  Female 2000-06-18  106428.0   True  NaN
781      Lawrence    Male 1995-07-03   46378.0  False  NaN
794        Nicole  Female 2004-03-01   44021.0  False  NaN
826           NaN     NaN 1988-08-01   87103.0   True  NaN
850       Charles    Male 1997-09-03  148291.0  False  NaN
851         Bobby    Male 1996-08-19  147842.0   True  NaN
853       Mildred  Female 2007-04-06  139284.0   True  NaN
855       Phillip     NaN 2003-10-20   89700.0   True  NaN
864          Ryan    Male 2012-11-16   57292.0  False  NaN
912           Joe    Male 1998-12-08  126120.0  False  NaN
951           NaN  Female 2010-09-14  143638.0   True  NaN
1000          NaN     NaN        NaT       NaN   True  NaN

In [41]:
ep[ep['Team'].notnull()]

    First Name  Gender Start Date    Salary   Mgmt          Team
0      Douglas    Male 1993-08-06       NaN   True     Marketing
2        Maria  Female        NaT  130590.0  False       Finance
3        Jerry     NaN 2005-03-04  138705.0   True       Finance
4        Larry    Male 1998-01-24  101004.0   True            IT
5       Dennis    Male 1987-04-18  115163.0  False         Legal
..         ...     ...        ...       ...    ...           ...
995      Henry     NaN 2014-11-23  132483.0  False  Distribution
996    Phillip    Male 1984-01-31   42392.0  False       Finance
997    Russell    Male 2013-05-20   96914.0  False       Product
998      Larry    Male 2013-04-20   60500.0  False  Business Dev
999     Albert    Male 2012-05-15  129949.0   True         Sales

[957 rows x 6 columns]

In [42]:
ep.dropna()

    First Name  Gender Start Date    Salary   Mgmt          Team
4        Larry    Male 1998-01-24  101004.0   True            IT
5       Dennis    Male 1987-04-18  115163.0  False         Legal
6         Ruby  Female 1987-08-17   65476.0   True       Product
8       Angela  Female 2005-11-22   95570.0   True   Engineering
9      Frances  Female 2002-08-08  139852.0   True  Business Dev
..         ...     ...        ...       ...    ...           ...
994     George    Male 2013-06-21   98874.0   True     Marketing
996    Phillip    Male 1984-01-31   42392.0  False       Finance
997    Russell    Male 2013-05-20   96914.0  False       Product
998      Larry    Male 2013-04-20   60500.0  False  Business Dev
999     Albert    Male 2012-05-15  129949.0   True         Sales

[761 rows x 6 columns]

In [43]:
ep.dropna(how='all') # default : 'any'

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
2         Maria  Female        NaT  130590.0  False       Finance
3         Jerry     NaN 2005-03-04  138705.0   True       Finance
4         Larry    Male 1998-01-24  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN   True           NaN

[1001 rows x 6 columns]

In [46]:
ep.dropna(subset=['Gender','Team'])

    First Name  Gender Start Date    Salary   Mgmt          Team
0      Douglas    Male 1993-08-06       NaN   True     Marketing
2        Maria  Female        NaT  130590.0  False       Finance
4        Larry    Male 1998-01-24  101004.0   True            IT
5       Dennis    Male 1987-04-18  115163.0  False         Legal
6         Ruby  Female 1987-08-17   65476.0   True       Product
..         ...     ...        ...       ...    ...           ...
994     George    Male 2013-06-21   98874.0   True     Marketing
996    Phillip    Male 1984-01-31   42392.0  False       Finance
997    Russell    Male 2013-05-20   96914.0  False       Product
998      Larry    Male 2013-04-20   60500.0  False  Business Dev
999     Albert    Male 2012-05-15  129949.0   True         Sales

[815 rows x 6 columns]

In [48]:
ep.dropna(thresh=4)

    First Name  Gender Start Date    Salary   Mgmt          Team
0      Douglas    Male 1993-08-06       NaN   True     Marketing
1       Thomas    Male 1996-03-31   61933.0   True           NaN
2        Maria  Female        NaT  130590.0  False       Finance
3        Jerry     NaN 2005-03-04  138705.0   True       Finance
4        Larry    Male 1998-01-24  101004.0   True            IT
..         ...     ...        ...       ...    ...           ...
995      Henry     NaN 2014-11-23  132483.0  False  Distribution
996    Phillip    Male 1984-01-31   42392.0  False       Finance
997    Russell    Male 2013-05-20   96914.0  False       Product
998      Larry    Male 2013-04-20   60500.0  False  Business Dev
999     Albert    Male 2012-05-15  129949.0   True         Sales

[999 rows x 6 columns]

In [49]:
ep['Team'].duplicated()

0       False
1       False
2       False
3        True
4       False
        ...
996      True
997      True
998      True
999      True
1000     True
Name: Team, Length: 1001, dtype: bool

In [50]:
ep[ep['Team'].duplicated()]

     First Name  Gender Start Date    Salary   Mgmt          Team
3         Jerry     NaN 2005-03-04  138705.0   True       Finance
7           NaN  Female 2015-07-20   45906.0   True       Finance
10       Louise  Female 1980-08-12   63241.0   True           NaN
11        Julie  Female 1997-10-26  102508.0   True         Legal
14     Kimberly  Female 1999-01-14   41426.0   True       Finance
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN   True           NaN

[990 rows x 6 columns]

In [51]:
ep[~ep['Team'].duplicated()]

   First Name  Gender Start Date    Salary   Mgmt          Team
0     Douglas    Male 1993-08-06       NaN   True     Marketing
1      Thomas    Male 1996-03-31   61933.0   True           NaN
2       Maria  Female        NaT  130590.0  False       Finance
4       Larry    Male 1998-01-24  101004.0   True            IT
5      Dennis    Male 1987-04-18  115163.0  False         Legal
6        Ruby  Female 1987-08-17   65476.0   True       Product
8      Angela  Female 2005-11-22   95570.0   True   Engineering
9     Frances  Female 2002-08-08  139852.0   True  Business Dev
12    Brandon    Male 1980-12-01  112807.0   True            HR
13       Gary    Male 2008-01-27  109831.0  False         Sales
40    Michael    Male 2008-10-10   99283.0   True  Distribution

In [53]:
ep['Team'].duplicated(keep='last')

0        True
1        True
2        True
3        True
4        True
        ...
996     False
997     False
998     False
999     False
1000    False
Name: Team, Length: 1001, dtype: bool

In [55]:
ep.drop_duplicates(subset=['Team'])

   First Name  Gender Start Date    Salary   Mgmt          Team
0     Douglas    Male 1993-08-06       NaN   True     Marketing
1      Thomas    Male 1996-03-31   61933.0   True           NaN
2       Maria  Female        NaT  130590.0  False       Finance
4       Larry    Male 1998-01-24  101004.0   True            IT
5      Dennis    Male 1987-04-18  115163.0  False         Legal
6        Ruby  Female 1987-08-17   65476.0   True       Product
8      Angela  Female 2005-11-22   95570.0   True   Engineering
9     Frances  Female 2002-08-08  139852.0   True  Business Dev
12    Brandon    Male 1980-12-01  112807.0   True            HR
13       Gary    Male 2008-01-27  109831.0  False         Sales
40    Michael    Male 2008-10-10   99283.0   True  Distribution

In [57]:
ep.drop_duplicates(subset=['Team'],keep='last')

     First Name  Gender Start Date    Salary   Mgmt          Team
988       Alice  Female 2004-10-05   47638.0  False            HR
989      Justin     NaN 1991-02-10   38344.0  False         Legal
990       Robin  Female 1987-07-24  100765.0   True            IT
993        Tina  Female 1997-05-15   56450.0   True   Engineering
994      George    Male 2013-06-21   98874.0   True     Marketing
995       Henry     NaN 2014-11-23  132483.0  False  Distribution
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN   True           NaN

In [56]:
ep.drop_duplicates(subset=['First Name'],keep=False)

    First Name  Gender Start Date    Salary   Mgmt          Team
5       Dennis    Male 1987-04-18  115163.0  False         Legal
8       Angela  Female 2005-11-22   95570.0   True   Engineering
33        Jean  Female 1993-12-18  119082.0  False  Business Dev
190      Carol  Female 1996-03-19   57783.0  False       Finance
291      Tammy  Female 1984-11-11  132839.0   True            IT
495     Eugene    Male 1984-05-24   81077.0  False         Sales
688      Brian    Male 2007-04-07   93901.0   True         Legal
832      Keith    Male 2003-02-12  120672.0  False         Legal
887      David    Male 2009-12-05   92242.0  False         Legal