In [1]:
import pandas as pd
import numpy as np

In [7]:
ds = pd.read_csv('./data/sales_by_employee.csv',parse_dates=["Date"],date_format='%m/%d/%y')
ds

         Date     Name           Customer  Revenue  Expenses
0  2020-01-01    Oscar      Logistics XYZ     5250       531
1  2020-01-01    Oscar        Money Corp.     4406       661
2  2020-01-02    Oscar         PaperMaven     8661      1401
3  2020-01-03    Oscar        PaperGenius     7075       906
4  2020-01-04    Oscar        Paper Pound     2524      1767
5  2020-01-05    Oscar        Paper Pound     2793       624
6  2020-01-01  Michael      Logistics XYZ     7172       412
7  2020-01-02  Michael        PaperGenius     6362       685
8  2020-01-03  Michael        PaperGenius     5982      1772
9  2020-01-04  Michael     Best Paper Co.     7917      1857
10 2020-01-05  Michael     Best Paper Co.     7837      1633
11 2020-01-01      Jim        PaperGenius     1864      1305
12 2020-01-02      Jim        Money Corp.     8278       462
13 2020-01-03      Jim        Paper Pound     4226      1923
14 2020-01-04      Jim         PaperMaven     3868      1889
15 2020-01-04      Jim  Average Paper Co.     2287       426
16 2020-01-01   Dwight        PaperGenius     2639       368
17 2020-01-03   Dwight      Logistics XYZ     4951       758
18 2020-01-03   Dwight     Best Paper Co.     2703      1321
19 2020-01-03   Dwight      Logistics XYZ     4258      1202
20 2020-01-05   Dwight        Paper Pound     7771      1475
21 2020-01-01    Creed        Money Corp.     4430       548
22 2020-01-02    Creed  Average Paper Co.     8026      1906
23 2020-01-02    Creed  Average Paper Co.     5188      1768
24 2020-01-04    Creed         PaperMaven     3144      1314
25 2020-01-05    Creed        Money Corp.      938      1053

### Pivot_table

In [13]:
ds.pivot_table(index='Date',aggfunc='sum',values='Expenses')

            Expenses
Date
2020-01-01      3825
2020-01-02      6222
2020-01-03      7882
2020-01-04      7253
2020-01-05      4785

In [14]:
ds.pivot_table(index='Date',aggfunc='sum',values=['Expenses','Revenue'])

            Expenses  Revenue
Date
2020-01-01      3825    25761
2020-01-02      6222    36515
2020-01-03      7882    29195
2020-01-04      7253    19740
2020-01-05      4785    19339

In [15]:
ds.pivot_table(index='Date',aggfunc='mean',values=['Expenses','Revenue'])

               Expenses      Revenue
Date
2020-01-01   637.500000  4293.500000
2020-01-02  1244.400000  7303.000000
2020-01-03  1313.666667  4865.833333
2020-01-04  1450.600000  3948.000000
2020-01-05  1196.250000  4834.750000

In [17]:
ds.pivot_table(index='Date',aggfunc='sum',values=['Expenses','Revenue'],columns='Name')

           Expenses                                  Revenue                   \
Name          Creed  Dwight     Jim Michael   Oscar    Creed   Dwight     Jim
Date
2020-01-01    548.0   368.0  1305.0   412.0  1192.0   4430.0   2639.0  1864.0
2020-01-02   3674.0     NaN   462.0   685.0  1401.0  13214.0      NaN  8278.0
2020-01-03      NaN  3281.0  1923.0  1772.0   906.0      NaN  11912.0  4226.0
2020-01-04   1314.0     NaN  2315.0  1857.0  1767.0   3144.0      NaN  6155.0
2020-01-05   1053.0  1475.0     NaN  1633.0   624.0    938.0   7771.0     NaN


Name       Michael   Oscar
Date
2020-01-01  7172.0  9656.0
2020-01-02  6362.0  8661.0
2020-01-03  5982.0  7075.0
2020-01-04  7917.0  2524.0
2020-01-05  7837.0  2793.0

In [18]:
ds.pivot_table(index='Date',aggfunc='sum',values=['Expenses','Revenue'],columns='Name',margins=True)

                    Expenses                                         Revenue  \
Name                   Creed  Dwight     Jim Michael   Oscar    All    Creed
Date
2020-01-01 00:00:00    548.0   368.0  1305.0   412.0  1192.0   3825   4430.0
2020-01-02 00:00:00   3674.0     NaN   462.0   685.0  1401.0   6222  13214.0
2020-01-03 00:00:00      NaN  3281.0  1923.0  1772.0   906.0   7882      NaN
2020-01-04 00:00:00   1314.0     NaN  2315.0  1857.0  1767.0   7253   3144.0
2020-01-05 00:00:00   1053.0  1475.0     NaN  1633.0   624.0   4785    938.0
All                   6589.0  5124.0  6005.0  6359.0  5890.0  29967  21726.0


Name                  Dwight      Jim  Michael    Oscar     All
Date
2020-01-01 00:00:00   2639.0   1864.0   7172.0   9656.0   25761
2020-01-02 00:00:00      NaN   8278.0   6362.0   8661.0   36515
2020-01-03 00:00:00  11912.0   4226.0   5982.0   7075.0   29195
2020-01-04 00:00:00      NaN   6155.0   7917.0   2524.0   19740
2020-01-05 00:00:00   7771.0      NaN   7837.0   2793.0   19339
All                  22322.0  20523.0  35270.0  30709.0  130550

In [22]:
ds.pivot_table(index='Date',aggfunc='sum',values=['Expenses','Revenue'],columns='Name',margins=True,margins_name='Total')

                    Expenses                                         Revenue  \
Name                   Creed  Dwight     Jim Michael   Oscar  Total    Creed
Date
2020-01-01 00:00:00    548.0   368.0  1305.0   412.0  1192.0   3825   4430.0
2020-01-02 00:00:00   3674.0     NaN   462.0   685.0  1401.0   6222  13214.0
2020-01-03 00:00:00      NaN  3281.0  1923.0  1772.0   906.0   7882      NaN
2020-01-04 00:00:00   1314.0     NaN  2315.0  1857.0  1767.0   7253   3144.0
2020-01-05 00:00:00   1053.0  1475.0     NaN  1633.0   624.0   4785    938.0
Total                 6589.0  5124.0  6005.0  6359.0  5890.0  29967  21726.0


Name                  Dwight      Jim  Michael    Oscar   Total
Date
2020-01-01 00:00:00   2639.0   1864.0   7172.0   9656.0   25761
2020-01-02 00:00:00      NaN   8278.0   6362.0   8661.0   36515
2020-01-03 00:00:00  11912.0   4226.0   5982.0   7075.0   29195
2020-01-04 00:00:00      NaN   6155.0   7917.0   2524.0   19740
2020-01-05 00:00:00   7771.0      NaN   7837.0   2793.0   19339
Total                22322.0  20523.0  35270.0  30709.0  130550

In [23]:
ds.pivot_table(index='Date',aggfunc='sum',values=['Expenses','Revenue'],columns='Name',margins=True,margins_name='Total',fill_value=0)

                    Expenses                                   Revenue         \
Name                   Creed Dwight   Jim Michael Oscar  Total   Creed Dwight
Date
2020-01-01 00:00:00      548    368  1305     412  1192   3825    4430   2639
2020-01-02 00:00:00     3674      0   462     685  1401   6222   13214      0
2020-01-03 00:00:00        0   3281  1923    1772   906   7882       0  11912
2020-01-04 00:00:00     1314      0  2315    1857  1767   7253    3144      0
2020-01-05 00:00:00     1053   1475     0    1633   624   4785     938   7771
Total                   6589   5124  6005    6359  5890  29967   21726  22322


Name                   Jim Michael  Oscar   Total
Date
2020-01-01 00:00:00   1864    7172   9656   25761
2020-01-02 00:00:00   8278    6362   8661   36515
2020-01-03 00:00:00   4226    5982   7075   29195
2020-01-04 00:00:00   6155    7917   2524   19740
2020-01-05 00:00:00      0    7837   2793   19339
Total                20523   35270  30709  130550

In [24]:
ds.pivot_table(index='Date',aggfunc='sum',values='Revenue',columns='Name')

Name          Creed   Dwight     Jim  Michael   Oscar
Date
2020-01-01   4430.0   2639.0  1864.0   7172.0  9656.0
2020-01-02  13214.0      NaN  8278.0   6362.0  8661.0
2020-01-03      NaN  11912.0  4226.0   5982.0  7075.0
2020-01-04   3144.0      NaN  6155.0   7917.0  2524.0
2020-01-05    938.0   7771.0     NaN   7837.0  2793.0

In [25]:
ds.pivot_table(index='Date',aggfunc=['sum','count'],values='Revenue',columns='Name')

                sum                                  count              \
Name          Creed   Dwight     Jim Michael   Oscar Creed Dwight  Jim
Date
2020-01-01   4430.0   2639.0  1864.0  7172.0  9656.0   1.0    1.0  1.0
2020-01-02  13214.0      NaN  8278.0  6362.0  8661.0   2.0    NaN  1.0
2020-01-03      NaN  11912.0  4226.0  5982.0  7075.0   NaN    3.0  1.0
2020-01-04   3144.0      NaN  6155.0  7917.0  2524.0   1.0    NaN  2.0
2020-01-05    938.0   7771.0     NaN  7837.0  2793.0   1.0    1.0  NaN


Name       Michael Oscar
Date
2020-01-01     1.0   2.0
2020-01-02     1.0   1.0
2020-01-03     1.0   1.0
2020-01-04     1.0   1.0
2020-01-05     1.0   1.0

In [28]:
ds.pivot_table(index='Date',aggfunc=['sum','mean'],values=['Expenses','Revenue'],columns='Name')

                sum                                                            \
           Expenses                                  Revenue
Name          Creed  Dwight     Jim Michael   Oscar    Creed   Dwight     Jim
Date
2020-01-01    548.0   368.0  1305.0   412.0  1192.0   4430.0   2639.0  1864.0
2020-01-02   3674.0     NaN   462.0   685.0  1401.0  13214.0      NaN  8278.0
2020-01-03      NaN  3281.0  1923.0  1772.0   906.0      NaN  11912.0  4226.0
2020-01-04   1314.0     NaN  2315.0  1857.0  1767.0   3144.0      NaN  6155.0
2020-01-05   1053.0  1475.0     NaN  1633.0   624.0    938.0   7771.0     NaN

                               mean                                       \
                           Expenses
Name       Michael   Oscar    Creed       Dwight     Jim Michael   Oscar
Date
2020-01-01  7172.0  9656.0    548.0   368.000000  1305.0   412.0   596.0
2020-01-02  6362.0  8661.0   1837.0          NaN   462.0   685.0  1401.0
2020-01-03  5982.0  7075.0      NaN  1093.666667  1923.0  1772.0   906.0
2020-01-04  7917.0  2524.0   1314.0          NaN  1157.5  1857.0  1767.0
2020-01-05  7837.0  2793.0   1053.0  1475.000000     NaN  1633.0   624.0


           Revenue
Name         Creed       Dwight     Jim Michael   Oscar
Date
2020-01-01  4430.0  2639.000000  1864.0  7172.0  4828.0
2020-01-02  6607.0          NaN  8278.0  6362.0  8661.0
2020-01-03     NaN  3970.666667  4226.0  5982.0  7075.0
2020-01-04  3144.0          NaN  3077.5  7917.0  2524.0
2020-01-05   938.0  7771.000000     NaN  7837.0  2793.0

In [29]:
ds.pivot_table(index='Date',aggfunc={'Expenses':'mean','Revenue':'count'},values=['Expenses','Revenue'],columns='Name')

           Expenses                                      Revenue              \
Name          Creed       Dwight     Jim Michael   Oscar   Creed Dwight  Jim
Date
2020-01-01    548.0   368.000000  1305.0   412.0   596.0     1.0    1.0  1.0
2020-01-02   1837.0          NaN   462.0   685.0  1401.0     2.0    NaN  1.0
2020-01-03      NaN  1093.666667  1923.0  1772.0   906.0     NaN    3.0  1.0
2020-01-04   1314.0          NaN  1157.5  1857.0  1767.0     1.0    NaN  2.0
2020-01-05   1053.0  1475.000000     NaN  1633.0   624.0     1.0    1.0  NaN


Name       Michael Oscar
Date
2020-01-01     1.0   2.0
2020-01-02     1.0   1.0
2020-01-03     1.0   1.0
2020-01-04     1.0   1.0
2020-01-05     1.0   1.0

In [32]:
ds.pivot_table(index=['Name','Date'],aggfunc='sum',values='Revenue')

                    Revenue
Name    Date
Creed   2020-01-01     4430
        2020-01-02    13214
        2020-01-04     3144
        2020-01-05      938
Dwight  2020-01-01     2639
        2020-01-03    11912
        2020-01-05     7771
Jim     2020-01-01     1864
        2020-01-02     8278
        2020-01-03     4226
        2020-01-04     6155
Michael 2020-01-01     7172
        2020-01-02     6362
        2020-01-03     5982
        2020-01-04     7917
        2020-01-05     7837
Oscar   2020-01-01     9656
        2020-01-02     8661
        2020-01-03     7075
        2020-01-04     2524
        2020-01-05     2793

In [33]:
ds.pivot_table(index=['Date','Name'],aggfunc='sum',values='Revenue')

                    Revenue
Date       Name
2020-01-01 Creed       4430
           Dwight      2639
           Jim         1864
           Michael     7172
           Oscar       9656
2020-01-02 Creed      13214
           Jim         8278
           Michael     6362
           Oscar       8661
2020-01-03 Dwight     11912
           Jim         4226
           Michael     5982
           Oscar       7075
2020-01-04 Creed       3144
           Jim         6155
           Michael     7917
           Oscar       2524
2020-01-05 Creed        938
           Dwight      7771
           Michael     7837
           Oscar       2793

In [34]:
ds.pivot_table(index=['Date','Name'],aggfunc='sum',values='Revenue').index

MultiIndex([('2020-01-01',   'Creed'),
            ('2020-01-01',  'Dwight'),
            ('2020-01-01',     'Jim'),
            ('2020-01-01', 'Michael'),
            ('2020-01-01',   'Oscar'),
            ('2020-01-02',   'Creed'),
            ('2020-01-02',     'Jim'),
            ('2020-01-02', 'Michael'),
            ('2020-01-02',   'Oscar'),
            ('2020-01-03',  'Dwight'),
            ('2020-01-03',     'Jim'),
            ('2020-01-03', 'Michael'),
            ('2020-01-03',   'Oscar'),
            ('2020-01-04',   'Creed'),
            ('2020-01-04',     'Jim'),
            ('2020-01-04', 'Michael'),
            ('2020-01-04',   'Oscar'),
            ('2020-01-05',   'Creed'),
            ('2020-01-05',  'Dwight'),
            ('2020-01-05', 'Michael'),
            ('2020-01-05',   'Oscar')],
           names=['Date', 'Name'])

### Stack/Unstack

In [37]:
new = ds.pivot_table(index=['Name'],aggfunc='sum',values='Revenue',columns='Date')
new

Date     2020-01-01  2020-01-02  2020-01-03  2020-01-04  2020-01-05
Name
Creed        4430.0     13214.0         NaN      3144.0       938.0
Dwight       2639.0         NaN     11912.0         NaN      7771.0
Jim          1864.0      8278.0      4226.0      6155.0         NaN
Michael      7172.0      6362.0      5982.0      7917.0      7837.0
Oscar        9656.0      8661.0      7075.0      2524.0      2793.0

In [38]:
new.stack()

Name     Date
Creed    2020-01-01     4430.0
         2020-01-02    13214.0
         2020-01-04     3144.0
         2020-01-05      938.0
Dwight   2020-01-01     2639.0
         2020-01-03    11912.0
         2020-01-05     7771.0
Jim      2020-01-01     1864.0
         2020-01-02     8278.0
         2020-01-03     4226.0
         2020-01-04     6155.0
Michael  2020-01-01     7172.0
         2020-01-02     6362.0
         2020-01-03     5982.0
         2020-01-04     7917.0
         2020-01-05     7837.0
Oscar    2020-01-01     9656.0
         2020-01-02     8661.0
         2020-01-03     7075.0
         2020-01-04     2524.0
         2020-01-05     2793.0
dtype: float64

In [43]:
new = ds.pivot_table(index=['Name','Customer'],aggfunc='sum',values='Revenue')
new

                           Revenue
Name    Customer
Creed   Average Paper Co.    13214
        Money Corp.           5368
        PaperMaven            3144
Dwight  Best Paper Co.        2703
        Logistics XYZ         9209
        Paper Pound           7771
        PaperGenius           2639
Jim     Average Paper Co.     2287
        Money Corp.           8278
        Paper Pound           4226
        PaperGenius           1864
        PaperMaven            3868
Michael Best Paper Co.       15754
        Logistics XYZ         7172
        PaperGenius          12344
Oscar   Logistics XYZ         5250
        Money Corp.           4406
        Paper Pound           5317
        PaperGenius           7075
        PaperMaven            8661

In [44]:
new.unstack()

                   Revenue                                           \
Customer Average Paper Co. Best Paper Co. Logistics XYZ Money Corp.
Name
Creed              13214.0            NaN           NaN      5368.0
Dwight                 NaN         2703.0        9209.0         NaN
Jim                 2287.0            NaN           NaN      8278.0
Michael                NaN        15754.0        7172.0         NaN
Oscar                  NaN            NaN        5250.0      4406.0


Customer Paper Pound PaperGenius PaperMaven
Name
Creed            NaN         NaN     3144.0
Dwight        7771.0      2639.0        NaN
Jim           4226.0      1864.0     3868.0
Michael          NaN     12344.0        NaN
Oscar         5317.0      7075.0     8661.0

### Explode

In [51]:
r = pd.read_csv('data/recipes.csv')
r

                    Recipe                                        Ingredients
0   Cashew Crusted Chicken  Apricot preserves, Dijon mustard, curry powder...
1      Tomato Basil Salmon  Salmon filets, basil, tomato, olive oil, Parme...
2  Parmesan Cheese Chicken  Bread crumbs, Parmesan cheese, Italian seasoni...

In [52]:
r['Ingredients']=r['Ingredients'].str.split(',')
r

                    Recipe                                        Ingredients
0   Cashew Crusted Chicken  [Apricot preserves,  Dijon mustard,  curry pow...
1      Tomato Basil Salmon  [Salmon filets,  basil,  tomato,  olive oil,  ...
2  Parmesan Cheese Chicken  [Bread crumbs,  Parmesan cheese,  Italian seas...

In [56]:
r.explode(column='Ingredients')

                    Recipe         Ingredients
0   Cashew Crusted Chicken   Apricot preserves
0   Cashew Crusted Chicken       Dijon mustard
0   Cashew Crusted Chicken        curry powder
0   Cashew Crusted Chicken     chicken breasts
0   Cashew Crusted Chicken             cashews
1      Tomato Basil Salmon       Salmon filets
1      Tomato Basil Salmon               basil
1      Tomato Basil Salmon              tomato
1      Tomato Basil Salmon           olive oil
1      Tomato Basil Salmon     Parmesan cheese
2  Parmesan Cheese Chicken        Bread crumbs
2  Parmesan Cheese Chicken     Parmesan cheese
2  Parmesan Cheese Chicken   Italian seasoning
2  Parmesan Cheese Chicken                 egg
2  Parmesan Cheese Chicken     chicken breasts

### Melt

In [58]:
vg = pd.read_csv('data/video_game_sales.csv')
vg

,Name,NA,EU,JP,Other
0,Wii Sports,41.49,29.02,3.77,8.46
1,Super Mario Bros.,29.08,3.58,6.81,0.77
2,Mario Kart Wii,15.85,12.88,3.79,3.31
3,Wii Sports Resort,15.75,11.01,3.28,2.96
4,Pokemon Red/Pokemon Blue,11.27,8.89,10.22,1.00
...,...,...,...,...,...
16561,Woody Woodpecker in Crazy Castle 5,0.01,0.00,0.00,0.00
16562,Men in Black II: Alien Escape,0.01,0.00,0.00,0.00
16563,SCORE International Baja 1000: The Official Game,0.00,0.00,0.00,0.00
16564,Know How 2,0.00,0.01,0.00,0.00
16565,Spirits & Spells,0.01,0.00,0.00,0.00

In [60]:
vg.melt(id_vars=['Name'],value_vars=['NA','EU'])

                                                   Name variable  value
0                                            Wii Sports       NA  41.49
1                                     Super Mario Bros.       NA  29.08
2                                        Mario Kart Wii       NA  15.85
3                                     Wii Sports Resort       NA  15.75
4                              Pokemon Red/Pokemon Blue       NA  11.27
...                                                 ...      ...    ...
33127                Woody Woodpecker in Crazy Castle 5       EU   0.00
33128                     Men in Black II: Alien Escape       EU   0.00
33129  SCORE International Baja 1000: The Official Game       EU   0.00
33130                                        Know How 2       EU   0.01
33131                                  Spirits & Spells       EU   0.00

[33132 rows x 3 columns]

In [63]:
vg.melt(id_vars=['Name'],value_vars=['NA','EU','JP','Other'])

                                                   Name variable  value
0                                            Wii Sports       NA  41.49
1                                     Super Mario Bros.       NA  29.08
2                                        Mario Kart Wii       NA  15.85
3                                     Wii Sports Resort       NA  15.75
4                              Pokemon Red/Pokemon Blue       NA  11.27
...                                                 ...      ...    ...
66259                Woody Woodpecker in Crazy Castle 5    Other   0.00
66260                     Men in Black II: Alien Escape    Other   0.00
66261  SCORE International Baja 1000: The Official Game    Other   0.00
66262                                        Know How 2    Other   0.00
66263                                  Spirits & Spells    Other   0.00

[66264 rows x 3 columns]

In [66]:
vg.melt(id_vars=['Name'],value_vars=['NA','EU','JP','Other'],value_name='Sales',var_name='Region')

                                                   Name Region  Sales
0                                            Wii Sports     NA  41.49
1                                     Super Mario Bros.     NA  29.08
2                                        Mario Kart Wii     NA  15.85
3                                     Wii Sports Resort     NA  15.75
4                              Pokemon Red/Pokemon Blue     NA  11.27
...                                                 ...    ...    ...
66259                Woody Woodpecker in Crazy Castle 5  Other   0.00
66260                     Men in Black II: Alien Escape  Other   0.00
66261  SCORE International Baja 1000: The Official Game  Other   0.00
66262                                        Know How 2  Other   0.00
66263                                  Spirits & Spells  Other   0.00

[66264 rows x 3 columns]