In [1]:
import pandas as pd
import numpy as np

In [2]:
g1 = pd.read_csv('data/groups1.csv')
g1

,group_id,name,category_id,city_id
0,6388,Alternative Health NYC,14,10001
1,6510,Alternative Energy Meetup,4,10001
2,8458,NYC Animal Rights,26,10001
3,8940,The New York City Anime Group,29,10001
4,10104,NYC Pit Bull Group,26,10001
...,...,...,...,...
7994,18875285,"NYC's Physically Fit, Active, & Athletic Singles",30,10001
7995,18876571,Shambhala Meditation Center NYC,14,10001
7996,18876811,Chicago Gophers,34,60601
7997,18877490,NYC Students & Young Entrepreneurs,2,10001
7998,18878056,NYC Green Bay Packer Fans Meetup,32,10001

In [3]:
g2 = pd.read_csv('data/groups2.csv')
g2

,group_id,name,category_id,city_id
0,18879327,BachataMania,5,10001
1,18880221,Photoshoot Chicago - Photography and Modeling ...,27,60601
2,18880426,Chicago Adult Push / Kick Scooter Group Riding...,31,60601
3,18880495,Chicago International Soccer Club,32,60601
4,18880695,Impact.tech San Francisco Meetup,2,94101
...,...,...,...,...
8326,26377464,Shinect,34,94101
8327,26377698,The art of getting what you want [conference s...,14,94101
8328,26378067,Streeterville Running Group,9,60601
8329,26378128,Just Dance NYC,23,10001
8330,26378470,FREE Arabic Chicago Evanston North Burbs,31,60601

In [4]:
cat = pd.read_csv('data/categories.csv')
cat

    category_id               category_name
0             1              Arts & Culture
1             3          Cars & Motorcycles
2             4     Community & Environment
3             5                     Dancing
4             6        Education & Learning
5             9                     Fitness
6            10                Food & Drink
7            11                       Games
8            14          Health & Wellbeing
9            15            Hobbies & Crafts
10           16  Language & Ethnic Identity
11           17                   Lifestyle
12           18                  Book Clubs
13           20               Movies & Film
14           21                       Music
15           22      New Age & Spirituality
16           23        Outdoors & Adventure
17           24                  Paranormal
18           25            Parents & Family
19           27                 Photography
20           28          Religion & Beliefs
21           29            Sci-Fi & Fantasy
22           30                     Singles
23           32         Sports & Recreation
24           33                     Support
25           36                     Writing
26           37               Miscellaneous

In [5]:
city = pd.read_csv('data/cities.csv',)
city

       id                 city state    zip
0    7093        West New York    NJ   7093
1   10001             New York    NY  10001
2   13417       New York Mills    NY  13417
3   46312         East Chicago    IN  46312
4   56567       New York Mills    MN  56567
5   60064        North Chicago    IL  60064
6   60185         West Chicago    IL  60185
7   60411      Chicago Heights    IL  60411
8   60415        Chicago Ridge    IL  60415
9   60601              Chicago    IL  60290
10  94080  South San Francisco    CA  94080
11  94101        San Francisco    CA  94101
12  95712         Chicago Park    CA  95712

In [6]:
city = pd.read_csv('data/cities.csv',dtype={'zip':'str'})
city

       id                 city state    zip
0    7093        West New York    NJ  07093
1   10001             New York    NY  10001
2   13417       New York Mills    NY  13417
3   46312         East Chicago    IN  46312
4   56567       New York Mills    MN  56567
5   60064        North Chicago    IL  60064
6   60185         West Chicago    IL  60185
7   60411      Chicago Heights    IL  60411
8   60415        Chicago Ridge    IL  60415
9   60601              Chicago    IL  60290
10  94080  South San Francisco    CA  94080
11  94101        San Francisco    CA  94101
12  95712         Chicago Park    CA  95712

In [7]:
pd.concat([g1,g2])

,group_id,name,category_id,city_id
0,6388,Alternative Health NYC,14,10001
1,6510,Alternative Energy Meetup,4,10001
2,8458,NYC Animal Rights,26,10001
3,8940,The New York City Anime Group,29,10001
4,10104,NYC Pit Bull Group,26,10001
...,...,...,...,...
8326,26377464,Shinect,34,94101
8327,26377698,The art of getting what you want [conference s...,14,94101
8328,26378067,Streeterville Running Group,9,60601
8329,26378128,Just Dance NYC,23,10001
8330,26378470,FREE Arabic Chicago Evanston North Burbs,31,60601

In [8]:
pd.concat([g1,g2],ignore_index=True)

,group_id,name,category_id,city_id
0,6388,Alternative Health NYC,14,10001
1,6510,Alternative Energy Meetup,4,10001
2,8458,NYC Animal Rights,26,10001
3,8940,The New York City Anime Group,29,10001
4,10104,NYC Pit Bull Group,26,10001
...,...,...,...,...
16325,26377464,Shinect,34,94101
16326,26377698,The art of getting what you want [conference s...,14,94101
16327,26378067,Streeterville Running Group,9,60601
16328,26378128,Just Dance NYC,23,10001
16329,26378470,FREE Arabic Chicago Evanston North Burbs,31,60601

In [10]:
groups = pd.concat([g1,g2],keys=['G1','G2'])
groups

         group_id                                               name  \
G1 0         6388                             Alternative Health NYC
   1         6510                          Alternative Energy Meetup
   2         8458                                  NYC Animal Rights
   3         8940                      The New York City Anime Group
   4        10104                                 NYC Pit Bull Group
...           ...                                                ...
G2 8326  26377464                                            Shinect
   8327  26377698  The art of getting what you want [conference s...
   8328  26378067                        Streeterville Running Group
   8329  26378128                                     Just Dance NYC
   8330  26378470           FREE Arabic Chicago Evanston North Burbs

         category_id  city_id
G1 0              14    10001
   1               4    10001
   2              26    10001
   3              29    10001
   4              26    10001
...              ...      ...
G2 8326           34    94101
   8327           14    94101
   8328            9    60601
   8329           23    10001
   8330           31    60601

[16330 rows x 4 columns]

In [12]:
groups.loc['G1',0]

group_id                         6388
name           Alternative Health NYC
category_id                        14
city_id                         10001
Name: (G1, 0), dtype: object

In [13]:
groups = pd.concat([g1,g2],ignore_index=True)
groups

,group_id,name,category_id,city_id
0,6388,Alternative Health NYC,14,10001
1,6510,Alternative Energy Meetup,4,10001
2,8458,NYC Animal Rights,26,10001
3,8940,The New York City Anime Group,29,10001
4,10104,NYC Pit Bull Group,26,10001
...,...,...,...,...
16325,26377464,Shinect,34,94101
16326,26377698,The art of getting what you want [conference s...,14,94101
16327,26378067,Streeterville Running Group,9,60601
16328,26378128,Just Dance NYC,23,10001
16329,26378470,FREE Arabic Chicago Evanston North Burbs,31,60601

In [14]:
groups.merge(right=cat,how='left',on='category_id')

,group_id,name,category_id,city_id,category_name
0,6388,Alternative Health NYC,14,10001,Health & Wellbeing
1,6510,Alternative Energy Meetup,4,10001,Community & Environment
2,8458,NYC Animal Rights,26,10001,NaN
3,8940,The New York City Anime Group,29,10001,Sci-Fi & Fantasy
4,10104,NYC Pit Bull Group,26,10001,NaN
...,...,...,...,...,...
16325,26377464,Shinect,34,94101,NaN
16326,26377698,The art of getting what you want [conference s...,14,94101,Health & Wellbeing
16327,26378067,Streeterville Running Group,9,60601,Fitness
16328,26378128,Just Dance NYC,23,10001,Outdoors & Adventure
16329,26378470,FREE Arabic Chicago Evanston North Burbs,31,60601,NaN

In [15]:
groups.merge(right=cat,how='inner',on='category_id')

,group_id,name,category_id,city_id,category_name
0,6388,Alternative Health NYC,14,10001,Health & Wellbeing
1,6510,Alternative Energy Meetup,4,10001,Community & Environment
2,8940,The New York City Anime Group,29,10001,Sci-Fi & Fantasy
3,10359,NYC International Arabic Language & Culture Club,16,10001,Language & Ethnic Identity
4,12111,The New York City American Sign Language Meetu...,16,10001,Language & Ethnic Identity
...,...,...,...,...,...
8032,26374579,Digital Film Academy Production Pitch,20,10001,Movies & Film
8033,26374655,Vocabulary workhop,16,94101,Language & Ethnic Identity
8034,26377698,The art of getting what you want [conference s...,14,94101,Health & Wellbeing
8035,26378067,Streeterville Running Group,9,60601,Fitness
8036,26378128,Just Dance NYC,23,10001,Outdoors & Adventure

In [17]:
groups.merge(right=cat,how='right',on='category_id')

,group_id,name,category_id,city_id,category_name
0,153288.0,Chicago Theater Goers Meetup Group,1,60601.0,Arts & Culture
1,178198.0,Union Square Reading Group,1,10001.0,Arts & Culture
2,234020.0,The San Francisco Figure Drawing Group,1,94101.0,Arts & Culture
3,292067.0,The San Francisco Play Reading Meetup Group,1,94101.0,Arts & Culture
4,297702.0,NEW YORK MUSEUM CLUB,1,10001.0,Arts & Culture
...,...,...,...,...,...
8033,26231454.0,We Love Diverse Stories,36,10001.0,Writing
8034,26246909.0,"Writing to Heal, Writing to Grow",36,10001.0,Writing
8035,26265769.0,Query Critique Group For Aspiring Authors,36,10001.0,Writing
8036,26318734.0,San Francisco UX Writers Meetup,36,94101.0,Writing
8037,NaN,NaN,37,NaN,Miscellaneous

In [18]:
groups.merge(right=cat,how='outer',on='category_id')

,group_id,name,category_id,city_id,category_name
0,153288.0,Chicago Theater Goers Meetup Group,1,60601.0,Arts & Culture
1,178198.0,Union Square Reading Group,1,10001.0,Arts & Culture
2,234020.0,The San Francisco Figure Drawing Group,1,94101.0,Arts & Culture
3,292067.0,The San Francisco Play Reading Meetup Group,1,94101.0,Arts & Culture
4,297702.0,NEW YORK MUSEUM CLUB,1,10001.0,Arts & Culture
...,...,...,...,...,...
16326,26231454.0,We Love Diverse Stories,36,10001.0,Writing
16327,26246909.0,"Writing to Heal, Writing to Grow",36,10001.0,Writing
16328,26265769.0,Query Critique Group For Aspiring Authors,36,10001.0,Writing
16329,26318734.0,San Francisco UX Writers Meetup,36,94101.0,Writing
16330,NaN,NaN,37,NaN,Miscellaneous

In [19]:
groups.merge(right=city,how='outer',left_on='city_id',right_on='id')

,group_id,name,category_id,city_id,id,city,state,zip
0,19525264.0,West NY | Hoboken | Social Group 20s & 30s,31.0,7093.0,7093,West New York,NJ,07093
1,20240670.0,Nerdy NJ/NY,11.0,7093.0,7093,West New York,NJ,07093
2,20395344.0,The Founding Moms' Exchange: North Jersey,2.0,7093.0,7093,West New York,NJ,07093
3,21130076.0,West New York Playdates for little ones,25.0,7093.0,7093,West New York,NJ,07093
4,21825714.0,Women~Wellness~Wisdom,14.0,7093.0,7093,West New York,NJ,07093
...,...,...,...,...,...,...,...,...
16329,26373602.0,Earndotcom: SF's most awesome digital currency...,34.0,94101.0,94101,San Francisco,CA,94101
16330,26374655.0,Vocabulary workhop,16.0,94101.0,94101,San Francisco,CA,94101
16331,26377464.0,Shinect,34.0,94101.0,94101,San Francisco,CA,94101
16332,26377698.0,The art of getting what you want [conference s...,14.0,94101.0,94101,San Francisco,CA,94101
16333,NaN,NaN,NaN,NaN,95712,Chicago Park,CA,95712

In [20]:
groups.merge(right=city,how='outer',left_on='city_id',right_on='id',indicator=True)

,group_id,name,category_id,city_id,id,city,state,zip,_merge
0,19525264.0,West NY | Hoboken | Social Group 20s & 30s,31.0,7093.0,7093,West New York,NJ,07093,both
1,20240670.0,Nerdy NJ/NY,11.0,7093.0,7093,West New York,NJ,07093,both
2,20395344.0,The Founding Moms' Exchange: North Jersey,2.0,7093.0,7093,West New York,NJ,07093,both
3,21130076.0,West New York Playdates for little ones,25.0,7093.0,7093,West New York,NJ,07093,both
4,21825714.0,Women~Wellness~Wisdom,14.0,7093.0,7093,West New York,NJ,07093,both
...,...,...,...,...,...,...,...,...,...
16329,26373602.0,Earndotcom: SF's most awesome digital currency...,34.0,94101.0,94101,San Francisco,CA,94101,both
16330,26374655.0,Vocabulary workhop,16.0,94101.0,94101,San Francisco,CA,94101,both
16331,26377464.0,Shinect,34.0,94101.0,94101,San Francisco,CA,94101,both
16332,26377698.0,The art of getting what you want [conference s...,14.0,94101.0,94101,San Francisco,CA,94101,both
16333,NaN,NaN,NaN,NaN,95712,Chicago Park,CA,95712,right_only