### NOTE:
- for jalali date use [this](https://github.com/ghodsizadeh/jalali-pandas)

In [1]:
import pandas as pd
import datetime
from pandas.tseries.offsets import DateOffset

In [2]:
pd.Timestamp(year=2000, month=1, day=1)

Timestamp('2000-01-01 00:00:00')

In [3]:
pd.Timestamp(year=2000, month=1, day=1) == datetime.datetime(2000, 1, 1)

True

In [4]:
pd.Timestamp(ts_input='2000-01-01')

Timestamp('2000-01-01 00:00:00')

In [5]:
pd.Timestamp(ts_input='2000/01/01')

Timestamp('2000-01-01 00:00:00')

In [6]:
pd.Timestamp(ts_input='05/29/2008')

Timestamp('2008-05-29 00:00:00')

In [7]:
pd.Timestamp(ts_input='05/29/2008 8:53:23 ')

Timestamp('2008-05-29 08:53:23')

In [8]:
pd.Timestamp(ts_input='05/29/2008 8:53:23 PM')

Timestamp('2008-05-29 20:53:23')

In [9]:
pd.Timestamp(ts_input=datetime.datetime(2008, 5, 29, 8, 53, 23))

Timestamp('2008-05-29 08:53:23')

In [10]:
pt = pd.Timestamp(ts_input=datetime.datetime(2008, 5, 29, 8, 53, 23))
pt

Timestamp('2008-05-29 08:53:23')

In [11]:
pt.year

2008

In [12]:
pt.month

5

In [13]:
pt.month_name()

'May'

In [14]:
pt.day

29

In [15]:
pt.week

22

In [16]:
pt.weekday()

3

In [17]:
pt.hour

8

In [18]:
pt.minute

53

In [19]:
pt.second

23

In [20]:
timestamps = [
    pd.Timestamp(year=2000, month=1, day=1),
    pd.Timestamp('2000-01-02'),
    pd.Timestamp('2000/01/03'),
]

se = pd.Series(['amir', 'kevin', 'jack'], index=timestamps)

In [21]:
se.index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03'], dtype='datetime64[ns]', freq=None)

In [22]:
timestamps = [
    datetime.datetime(2000, 1, 1),
    datetime.datetime(2000, 1, 2),
    datetime.datetime(2000, 1, 3),
]

se = pd.Series(['amir', 'kevin', 'jack'], index=timestamps)

In [23]:
se.index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03'], dtype='datetime64[ns]', freq=None)

In [24]:
timestamps = [
    datetime.datetime(2000, 1, 1),
    datetime.datetime(2000, 1, 2),
    datetime.datetime(2000, 1, 3),
]
index = pd.DatetimeIndex(timestamps)
se = pd.Series(['amir', 'kevin', 'jack'], index=index)

In [25]:
se.index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03'], dtype='datetime64[ns]', freq=None)

In [26]:
morning = pd.Timestamp('2020-02-03 11:23:54 Am')
evening = pd.Timestamp('2020-02-03 11:23:54 PM')
morning > evening

False

In [27]:
morning < evening

True

In [28]:
disney = pd.read_csv('data/disney.csv')
disney['Date'] = pd.to_datetime(disney['Date'])
disney

            Date        High         Low        Open       Close
0     1962-01-02    0.096026    0.092908    0.092908    0.092908
1     1962-01-03    0.094467    0.092908    0.092908    0.094155
2     1962-01-04    0.094467    0.093532    0.094155    0.094155
3     1962-01-05    0.094779    0.093844    0.094155    0.094467
4     1962-01-08    0.095714    0.092285    0.094467    0.094155
...          ...         ...         ...         ...         ...
14722 2020-06-26  111.199997  108.019997  110.949997  109.099998
14723 2020-06-29  111.570000  108.099998  109.000000  111.519997
14724 2020-06-30  112.050003  109.930000  111.500000  111.510002
14725 2020-07-01  115.599998  112.290001  112.820000  113.010002
14726 2020-07-02  115.099998  112.000000  115.000000  112.180000

[14727 rows x 5 columns]

In [29]:
disney.dtypes

Date     datetime64[ns]
High            float64
Low             float64
Open            float64
Close           float64
dtype: object

In [30]:
disney['Date'].dt.year

0        1962
1        1962
2        1962
3        1962
4        1962
         ...
14722    2020
14723    2020
14724    2020
14725    2020
14726    2020
Name: Date, Length: 14727, dtype: int32

In [31]:
disney['Date'].dt.month

0        1
1        1
2        1
3        1
4        1
        ..
14722    6
14723    6
14724    6
14725    7
14726    7
Name: Date, Length: 14727, dtype: int32

In [32]:
disney['Date'].dt.dayofweek

0        1
1        2
2        3
3        4
4        0
        ..
14722    4
14723    0
14724    1
14725    2
14726    3
Name: Date, Length: 14727, dtype: int32

In [33]:
disney['Date'].dt.day

0         2
1         3
2         4
3         5
4         8
         ..
14722    26
14723    29
14724    30
14725     1
14726     2
Name: Date, Length: 14727, dtype: int32

In [34]:
disney['Date'].dt.month_name()

0        January
1        January
2        January
3        January
4        January
          ...
14722       June
14723       June
14724       June
14725       July
14726       July
Name: Date, Length: 14727, dtype: object

In [35]:
disney['Date'].dt.day_name()

0          Tuesday
1        Wednesday
2         Thursday
3           Friday
4           Monday
           ...
14722       Friday
14723       Monday
14724      Tuesday
14725    Wednesday
14726     Thursday
Name: Date, Length: 14727, dtype: object

In [36]:
disney['week_day'] = disney['Date'].dt.day_name()
disney

            Date        High         Low        Open       Close   week_day
0     1962-01-02    0.096026    0.092908    0.092908    0.092908    Tuesday
1     1962-01-03    0.094467    0.092908    0.092908    0.094155  Wednesday
2     1962-01-04    0.094467    0.093532    0.094155    0.094155   Thursday
3     1962-01-05    0.094779    0.093844    0.094155    0.094467     Friday
4     1962-01-08    0.095714    0.092285    0.094467    0.094155     Monday
...          ...         ...         ...         ...         ...        ...
14722 2020-06-26  111.199997  108.019997  110.949997  109.099998     Friday
14723 2020-06-29  111.570000  108.099998  109.000000  111.519997     Monday
14724 2020-06-30  112.050003  109.930000  111.500000  111.510002    Tuesday
14725 2020-07-01  115.599998  112.290001  112.820000  113.010002  Wednesday
14726 2020-07-02  115.099998  112.000000  115.000000  112.180000   Thursday

[14727 rows x 6 columns]

In [37]:
g = disney.groupby('week_day')
g.mean(numeric_only=True)

                High        Low       Open      Close
week_day
Friday     23.767304  23.318898  23.552872  23.554498
Monday     23.377271  22.930606  23.161392  23.162543
Thursday   23.770234  23.288687  23.534561  23.540359
Tuesday    23.791234  23.335267  23.571755  23.562907
Wednesday  23.842743  23.355419  23.605618  23.609873

In [38]:
disney[disney['Date'].dt.is_quarter_start]

            Date        High         Low        Open       Close   week_day
189   1962-10-01    0.064849    0.062355    0.063913    0.062355     Monday
314   1963-04-01    0.087989    0.086704    0.087025    0.086704     Monday
377   1963-07-01    0.096338    0.095053    0.096338    0.095696     Monday
441   1963-10-01    0.110467    0.107898    0.107898    0.110467    Tuesday
565   1964-04-01    0.116248    0.112394    0.112394    0.116248  Wednesday
...          ...         ...         ...         ...         ...        ...
14409 2019-04-01  112.870003  111.379997  111.589996  112.510002     Monday
14472 2019-07-01  141.949997  139.220001  140.449997  141.649994     Monday
14536 2019-10-01  131.779999  129.509995  130.800003  129.550003    Tuesday
14662 2020-04-01   97.400002   92.559998   93.500000   94.919998  Wednesday
14725 2020-07-01  115.599998  112.290001  112.820000  113.010002  Wednesday

[123 rows x 6 columns]

In [39]:
disney[disney['Date'].dt.is_quarter_end]

            Date        High         Low        Open       Close week_day
251   1962-12-31    0.074501    0.071290    0.074501    0.072253   Monday
440   1963-09-30    0.109825    0.105972    0.108541    0.107577   Monday
502   1963-12-31    0.101476    0.096980    0.097622    0.101476  Tuesday
564   1964-03-31    0.115605    0.112394    0.114963    0.112394  Tuesday
628   1964-06-30    0.101476    0.100191    0.101476    0.100834  Tuesday
...          ...         ...         ...         ...         ...      ...
14347 2018-12-31  109.669998  107.550003  109.110001  109.650002   Monday
14535 2019-09-30  130.860001  129.820007  130.350006  130.320007   Monday
14599 2019-12-31  144.770004  143.259995  143.669998  144.630005  Tuesday
14661 2020-03-31  103.160004   96.160004  100.220001   96.599998  Tuesday
14724 2020-06-30  112.050003  109.930000  111.500000  111.510002  Tuesday

[163 rows x 6 columns]

In [40]:
disney[disney['Date'].dt.is_year_start]

Empty DataFrame
Columns: [Date, High, Low, Open, Close, week_day]
Index: []

In [41]:
disney[disney['Date'].dt.is_year_end]

            Date        High         Low        Open       Close   week_day
251   1962-12-31    0.074501    0.071290    0.074501    0.072253     Monday
502   1963-12-31    0.101476    0.096980    0.097622    0.101476    Tuesday
755   1964-12-31    0.117853    0.116890    0.116890    0.116890   Thursday
1007  1965-12-31    0.154141    0.150929    0.153498    0.152214     Friday
1736  1968-12-31    0.439301    0.431594    0.434163    0.436732    Tuesday
1986  1969-12-31    0.694275    0.678219    0.678219    0.688495  Wednesday
2240  1970-12-31    0.732168    0.721892    0.732168    0.726388   Thursday
2493  1971-12-31    1.430939    1.392404    1.392404    1.412956     Friday
2996  1973-12-31    0.983931    0.955672    0.973655    0.971086     Monday
3249  1974-12-31    0.441870    0.421318    0.421318    0.439301    Tuesday
3502  1975-12-31    1.030173    1.019897    1.019897    1.025035  Wednesday
3755  1976-12-31    0.999345    0.971086    0.994207    0.971086     Friday
4512  1979-12-31    0.929982    0.919706    0.927413    0.922275     Monday
4765  1980-12-31    1.061001    1.045587    1.048156    1.053294  Wednesday
5018  1981-12-31    1.078984    1.071277    1.073846    1.073846   Thursday
5271  1982-12-31    1.302488    1.292212    1.292212    1.299919     Friday
5777  1984-12-31    1.248539    1.230556    1.243401    1.230556     Monday
6029  1985-12-31    2.332661    2.281281    2.281281    2.319816    Tuesday
6282  1986-12-31    3.565786    3.483578    3.483578    3.545234  Wednesday
6535  1987-12-31    4.891396    4.809187    4.891396    4.870844   Thursday
7293  1990-12-31    8.405802    8.261937    8.395526    8.344146     Monday
7546  1991-12-31    9.484786    9.289541    9.443683    9.412854    Tuesday
7800  1992-12-31   14.468667   14.139833   14.304250   14.139833   Thursday
8053  1993-12-31   14.468667   14.016521   14.386458   14.016521     Friday
8811  1996-12-31   23.182751   22.812813   23.018333   22.936125    Tuesday
9064  1997-12-31   32.965542   32.451740   32.554501   32.554501  Wednesday
9316  1998-12-31   29.718313   29.163406   29.471687   29.594999   Thursday
9568  1999-12-31   28.978437   28.423531   28.731813   28.855125     Friday
10068 2001-12-31   20.963125   20.272575   20.667175   20.440281     Monday
10320 2002-12-31   16.227924   15.606430   15.734675   16.089815    Tuesday
10572 2003-12-31   23.133425   22.876934   22.995316   23.015045  Wednesday
10824 2004-12-31   27.622000   27.385241   27.602270   27.424700     Friday
11578 2007-12-31   32.520000   32.240002   32.419998   32.279999     Monday
11831 2008-12-31   22.950001   22.520000   22.570000   22.690001  Wednesday
12083 2009-12-31   32.750000   32.220001   32.270000   32.250000   Thursday
12335 2010-12-31   37.599998   37.209999   37.369999   37.509998     Friday
12837 2012-12-31   49.799999   48.799999   48.889999   49.790001     Monday
13089 2013-12-31   76.500000   75.809998   76.279999   76.400002    Tuesday
13341 2014-12-31   95.519997   94.029999   95.129997   94.190002  Wednesday
13593 2015-12-31  106.309998  105.059998  106.139999  105.080002   Thursday
14347 2018-12-31  109.669998  107.550003  109.110001  109.650002     Monday
14599 2019-12-31  144.770004  143.259995  143.669998  144.630005    Tuesday

In [42]:
disney['Date']

0       1962-01-02
1       1962-01-03
2       1962-01-04
3       1962-01-05
4       1962-01-08
           ...
14722   2020-06-26
14723   2020-06-29
14724   2020-06-30
14725   2020-07-01
14726   2020-07-02
Name: Date, Length: 14727, dtype: datetime64[ns]

In [43]:
disney['Date'] + DateOffset(days=5)

0       1962-01-07
1       1962-01-08
2       1962-01-09
3       1962-01-10
4       1962-01-13
           ...
14722   2020-07-01
14723   2020-07-04
14724   2020-07-05
14725   2020-07-06
14726   2020-07-07
Name: Date, Length: 14727, dtype: datetime64[ns]

In [44]:
disney['Date'] - DateOffset(days=3, hours=5)

0       1961-12-29 19:00:00
1       1961-12-30 19:00:00
2       1961-12-31 19:00:00
3       1962-01-01 19:00:00
4       1962-01-04 19:00:00
                ...
14722   2020-06-22 19:00:00
14723   2020-06-25 19:00:00
14724   2020-06-26 19:00:00
14725   2020-06-27 19:00:00
14726   2020-06-28 19:00:00
Name: Date, Length: 14727, dtype: datetime64[ns]

In [45]:
disney['Date'] + DateOffset(days=3, hours=-5)

0       1962-01-04 19:00:00
1       1962-01-05 19:00:00
2       1962-01-06 19:00:00
3       1962-01-07 19:00:00
4       1962-01-10 19:00:00
                ...
14722   2020-06-28 19:00:00
14723   2020-07-01 19:00:00
14724   2020-07-02 19:00:00
14725   2020-07-03 19:00:00
14726   2020-07-04 19:00:00
Name: Date, Length: 14727, dtype: datetime64[ns]

In [46]:
disney['Date']

0       1962-01-02
1       1962-01-03
2       1962-01-04
3       1962-01-05
4       1962-01-08
           ...
14722   2020-06-26
14723   2020-06-29
14724   2020-06-30
14725   2020-07-01
14726   2020-07-02
Name: Date, Length: 14727, dtype: datetime64[ns]

In [47]:
disney['Date'] + pd.offsets.MonthEnd()

0       1962-01-31
1       1962-01-31
2       1962-01-31
3       1962-01-31
4       1962-01-31
           ...
14722   2020-06-30
14723   2020-06-30
14724   2020-07-31
14725   2020-07-31
14726   2020-07-31
Name: Date, Length: 14727, dtype: datetime64[ns]

In [48]:
disney['Date'] - pd.offsets.MonthEnd()

0       1961-12-31
1       1961-12-31
2       1961-12-31
3       1961-12-31
4       1961-12-31
           ...
14722   2020-05-31
14723   2020-05-31
14724   2020-05-31
14725   2020-06-30
14726   2020-06-30
Name: Date, Length: 14727, dtype: datetime64[ns]

In [49]:
disney['Date'] + pd.offsets.MonthBegin()

0       1962-02-01
1       1962-02-01
2       1962-02-01
3       1962-02-01
4       1962-02-01
           ...
14722   2020-07-01
14723   2020-07-01
14724   2020-07-01
14725   2020-08-01
14726   2020-08-01
Name: Date, Length: 14727, dtype: datetime64[ns]

In [50]:
disney['Date'] - pd.offsets.MonthBegin()

0       1962-01-01
1       1962-01-01
2       1962-01-01
3       1962-01-01
4       1962-01-01
           ...
14722   2020-06-01
14723   2020-06-01
14724   2020-06-01
14725   2020-06-01
14726   2020-07-01
Name: Date, Length: 14727, dtype: datetime64[ns]

In [51]:
pd.Timedelta(days=8, hours=5, minutes=5)

Timedelta('8 days 05:05:00')

In [52]:
pd.to_timedelta('3 hours, 20 minutes,12 seconds')

Timedelta('0 days 03:20:12')

In [53]:
pd.to_timedelta([5, 10, 15], unit='d')

TimedeltaIndex(['5 days', '10 days', '15 days'], dtype='timedelta64[ns]', freq=None)

In [54]:
pd.Timestamp('1999-01-01') - pd.Timestamp('1998-12-22')

Timedelta('10 days 00:00:00')

In [55]:
pd.Timestamp('1999-01-01') - pd.Timestamp('1999-12-22')

Timedelta('-355 days +00:00:00')

In [57]:
dlv = pd.read_csv('data/deliveries.csv')
dlv

    order_date delivery_date
0      5/24/98        2/5/99
1      4/22/92        3/6/98
2      2/10/91       8/26/92
3      7/21/92      11/20/97
4       9/2/93       6/10/98
..         ...           ...
496    6/24/91        2/2/96
497     9/9/91       3/30/98
498   11/16/90       4/27/98
499     6/3/93       6/13/93
500     1/4/90       10/3/91

[501 rows x 2 columns]

In [60]:
dlv['order_date'] = pd.to_datetime(dlv['order_date'], format='%m/%d/%Y')
dlv['delivery_date'] = pd.to_datetime(dlv['delivery_date'], format='%m/%d/%Y')
dlv

    order_date delivery_date
0   1998-05-24    1999-02-05
1   1992-04-22    1998-03-06
2   1991-02-10    1992-08-26
3   1992-07-21    1997-11-20
4   1993-09-02    1998-06-10
..         ...           ...
496 1991-06-24    1996-02-02
497 1991-09-09    1998-03-30
498 1990-11-16    1998-04-27
499 1993-06-03    1993-06-13
500 1990-01-04    1991-10-03

[501 rows x 2 columns]

In [64]:
dlv['duration'] = dlv['delivery_date'] - dlv['order_date']
dlv

    order_date delivery_date  duration
0   1998-05-24    1999-02-05  257 days
1   1992-04-22    1998-03-06 2144 days
2   1991-02-10    1992-08-26  563 days
3   1992-07-21    1997-11-20 1948 days
4   1993-09-02    1998-06-10 1742 days
..         ...           ...       ...
496 1991-06-24    1996-02-02 1684 days
497 1991-09-09    1998-03-30 2394 days
498 1990-11-16    1998-04-27 2719 days
499 1993-06-03    1993-06-13   10 days
500 1990-01-04    1991-10-03  637 days

[501 rows x 3 columns]

In [68]:
dlv.sort_values('duration')

    order_date delivery_date  duration
454 1990-05-24    1990-06-01    8 days
294 1994-08-11    1994-08-20    9 days
10  1998-05-10    1998-05-19    9 days
499 1993-06-03    1993-06-13   10 days
143 1997-09-20    1997-10-06   16 days
..         ...           ...       ...
152 1990-09-18    1999-12-19 3379 days
62  1990-04-02    1999-08-16 3423 days
458 1990-02-13    1999-11-15 3562 days
145 1990-03-07    1999-12-25 3580 days
448 1990-01-20    1999-11-12 3583 days

[501 rows x 3 columns]

In [69]:
dlv.sort_values('duration', ascending=False)

    order_date delivery_date  duration
448 1990-01-20    1999-11-12 3583 days
145 1990-03-07    1999-12-25 3580 days
458 1990-02-13    1999-11-15 3562 days
62  1990-04-02    1999-08-16 3423 days
152 1990-09-18    1999-12-19 3379 days
..         ...           ...       ...
143 1997-09-20    1997-10-06   16 days
499 1993-06-03    1993-06-13   10 days
10  1998-05-10    1998-05-19    9 days
294 1994-08-11    1994-08-20    9 days
454 1990-05-24    1990-06-01    8 days

[501 rows x 3 columns]

In [71]:
dlv['duration'].mean()

Timedelta('1217 days 22:53:53.532934128')

In [72]:
dlv[dlv['duration']>pd.Timedelta(days=365)]

    order_date delivery_date  duration
1   1992-04-22    1998-03-06 2144 days
2   1991-02-10    1992-08-26  563 days
3   1992-07-21    1997-11-20 1948 days
4   1993-09-02    1998-06-10 1742 days
6   1990-01-25    1994-10-02 1711 days
..         ...           ...       ...
495 1990-12-10    1992-12-16  737 days
496 1991-06-24    1996-02-02 1684 days
497 1991-09-09    1998-03-30 2394 days
498 1990-11-16    1998-04-27 2719 days
500 1990-01-04    1991-10-03  637 days

[394 rows x 3 columns]

In [74]:
dlv[dlv['duration']>'365 days']

    order_date delivery_date  duration
1   1992-04-22    1998-03-06 2144 days
2   1991-02-10    1992-08-26  563 days
3   1992-07-21    1997-11-20 1948 days
4   1993-09-02    1998-06-10 1742 days
6   1990-01-25    1994-10-02 1711 days
..         ...           ...       ...
495 1990-12-10    1992-12-16  737 days
496 1991-06-24    1996-02-02 1684 days
497 1991-09-09    1998-03-30 2394 days
498 1990-11-16    1998-04-27 2719 days
500 1990-01-04    1991-10-03  637 days

[394 rows x 3 columns]