In [3]:
import pandas as pd
import numpy as np

## Json

In [6]:
nobel = pd.read_json('data/prize.json')
nobel

                                                prizes
0    {'year': '2022', 'category': 'chemistry', 'lau...
1    {'year': '2022', 'category': 'economics', 'lau...
2    {'year': '2022', 'category': 'literature', 'la...
3    {'year': '2022', 'category': 'peace', 'laureat...
4    {'year': '2022', 'category': 'physics', 'laure...
..                                                 ...
659  {'year': '1901', 'category': 'chemistry', 'lau...
660  {'year': '1901', 'category': 'literature', 'la...
661  {'year': '1901', 'category': 'peace', 'laureat...
662  {'year': '1901', 'category': 'physics', 'laure...
663  {'year': '1901', 'category': 'medicine', 'laur...

[664 rows x 1 columns]

In [7]:
nobel.loc[2]

prizes    {'year': '2022', 'category': 'literature', 'la...
Name: 2, dtype: object

In [9]:
second = nobel.loc[2]['prizes']
second

{'year': '2022',
 'category': 'literature',
 'laureates': [{'id': '1017',
   'firstname': 'Annie',
   'surname': 'Ernaux',
   'motivation': '"for the courage and clinical acuity with which she uncovers the roots, estrangements and  collective restraints of personal memory"',
   'share': '1'}]}

In [10]:
pd.json_normalize(second)

   year    category                                          laureates
0  2022  literature  [{'id': '1017', 'firstname': 'Annie', 'surname...

In [11]:
pd.json_normalize(second, record_path='laureates')

,id,firstname,surname,motivation,share
0,1017,Annie,Ernaux,"""for the courage and clinical acuity with whic...",1

In [13]:
pd.json_normalize(second, record_path='laureates', meta=['year', 'category'])

,id,firstname,surname,motivation,share,year,category
0,1017,Annie,Ernaux,"""for the courage and clinical acuity with whic...",1,2022,literature

In [14]:
winners = pd.json_normalize(nobel['prizes'], record_path='laureates', meta=['year', 'category'])

KeyError: "Key 'laureates' not found. If specifying a record_path, all elements of data should have the path."

In [18]:
def add_laureates_key(entry):
    entry.setdefault('laureates', [])


nobel['prizes'].apply(add_laureates_key)
winners = pd.json_normalize(nobel['prizes'], record_path='laureates', meta=['year', 'category'])
winners

,id,firstname,surname,motivation,share,year,category
0,1015,Carolyn,Bertozzi,"""for the development of click chemistry and bi...",3,2022,chemistry
1,1016,Morten,Meldal,"""for the development of click chemistry and bi...",3,2022,chemistry
2,743,Barry,Sharpless,"""for the development of click chemistry and bi...",3,2022,chemistry
3,1021,Ben,Bernanke,"""for research on banks and financial crises""",3,2022,economics
4,1022,Douglas,Diamond,"""for research on banks and financial crises""",3,2022,economics
...,...,...,...,...,...,...,...
984,569,Sully,Prudhomme,"""in special recognition of his poetic composit...",1,1901,literature
985,462,Henry,Dunant,"""for his humanitarian efforts to help wounded ...",2,1901,peace
986,463,Frédéric,Passy,"""for his lifelong work for international peace...",2,1901,peace
987,1,Wilhelm Conrad,Röntgen,"""in recognition of the extraordinary services ...",1,1901,physics
988,293,Emil,von Behring,"""for his work on serum therapy, especially its...",1,1901,medicine

In [19]:
winners.head()

,id,firstname,surname,motivation,share,year,category
0,1015,Carolyn,Bertozzi,"""for the development of click chemistry and bi...",3,2022,chemistry
1,1016,Morten,Meldal,"""for the development of click chemistry and bi...",3,2022,chemistry
2,743,Barry,Sharpless,"""for the development of click chemistry and bi...",3,2022,chemistry
3,1021,Ben,Bernanke,"""for research on banks and financial crises""",3,2022,economics
4,1022,Douglas,Diamond,"""for research on banks and financial crises""",3,2022,economics

In [20]:
winners.head().to_json()

'{"id":{"0":"1015","1":"1016","2":"743","3":"1021","4":"1022"},"firstname":{"0":"Carolyn","1":"Morten","2":"Barry","3":"Ben","4":"Douglas"},"surname":{"0":"Bertozzi","1":"Meldal","2":"Sharpless","3":"Bernanke","4":"Diamond"},"motivation":{"0":"\\"for the development of click chemistry and bioorthogonal chemistry\\"","1":"\\"for the development of click chemistry and bioorthogonal chemistry\\"","2":"\\"for the development of click chemistry and bioorthogonal chemistry\\"","3":"\\"for research on banks and financial crises\\"","4":"\\"for research on banks and financial crises\\""},"share":{"0":"3","1":"3","2":"3","3":"3","4":"3"},"year":{"0":"2022","1":"2022","2":"2022","3":"2022","4":"2022"},"category":{"0":"chemistry","1":"chemistry","2":"chemistry","3":"economics","4":"economics"}}'

In [21]:
winners.head().to_json(orient='records')

'[{"id":"1015","firstname":"Carolyn","surname":"Bertozzi","motivation":"\\"for the development of click chemistry and bioorthogonal chemistry\\"","share":"3","year":"2022","category":"chemistry"},{"id":"1016","firstname":"Morten","surname":"Meldal","motivation":"\\"for the development of click chemistry and bioorthogonal chemistry\\"","share":"3","year":"2022","category":"chemistry"},{"id":"743","firstname":"Barry","surname":"Sharpless","motivation":"\\"for the development of click chemistry and bioorthogonal chemistry\\"","share":"3","year":"2022","category":"chemistry"},{"id":"1021","firstname":"Ben","surname":"Bernanke","motivation":"\\"for research on banks and financial crises\\"","share":"3","year":"2022","category":"economics"},{"id":"1022","firstname":"Douglas","surname":"Diamond","motivation":"\\"for research on banks and financial crises\\"","share":"3","year":"2022","category":"economics"}]'

In [22]:
winners.head().to_json('data/new_price.json', orient='records')

## CSV

In [23]:
baby = pd.read_csv('data/Popular_Baby_Names.csv')
baby

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank
0,2011,FEMALE,HISPANIC,GERALDINE,13,75
1,2011,FEMALE,HISPANIC,GIA,21,67
2,2011,FEMALE,HISPANIC,GIANNA,49,42
3,2011,FEMALE,HISPANIC,GISELLE,38,51
4,2011,FEMALE,HISPANIC,GRACE,36,53
...,...,...,...,...,...,...
49504,2018,FEMALE,BLACK NON HISPANIC,Nala,10,40
49505,2018,FEMALE,BLACK NON HISPANIC,Royalty,10,40
49506,2018,FEMALE,BLACK NON HISPANIC,Sariyah,10,40
49507,2018,FEMALE,BLACK NON HISPANIC,Simone,10,40
49508,2018,FEMALE,BLACK NON HISPANIC,Zahra,10,40

In [24]:
baby.head().to_csv()

",Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank\r\n0,2011,FEMALE,HISPANIC,GERALDINE,13,75\r\n1,2011,FEMALE,HISPANIC,GIA,21,67\r\n2,2011,FEMALE,HISPANIC,GIANNA,49,42\r\n3,2011,FEMALE,HISPANIC,GISELLE,38,51\r\n4,2011,FEMALE,HISPANIC,GRACE,36,53\r\n"

In [25]:
baby.head().to_csv(index=False)

"Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank\r\n2011,FEMALE,HISPANIC,GERALDINE,13,75\r\n2011,FEMALE,HISPANIC,GIA,21,67\r\n2011,FEMALE,HISPANIC,GIANNA,49,42\r\n2011,FEMALE,HISPANIC,GISELLE,38,51\r\n2011,FEMALE,HISPANIC,GRACE,36,53\r\n"

In [26]:
baby.head().to_csv(index=False, columns=['Gender', 'Child\'s First Name'])

"Gender,Child's First Name\r\nFEMALE,GERALDINE\r\nFEMALE,GIA\r\nFEMALE,GIANNA\r\nFEMALE,GISELLE\r\nFEMALE,GRACE\r\n"

In [27]:
baby.head().to_csv('data/new_baby.csv', index=False, columns=['Gender', 'Child\'s First Name'])

## Excel
- For use excel in python and pandas must install `xlrd` and `openpyxl`

In [29]:
single = pd.read_excel('data/Single Worksheet.xlsx')
single

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [30]:
single = pd.read_excel('data/Single Worksheet.xlsx', usecols=[0, 1])
single

  First Name Last Name
0    Brandon     James
1       Sean   Hawkins
2       Judy       Day
3     Ashley      Ruiz
4  Stephanie     Gomez

In [34]:
single = pd.read_excel('data/Single Worksheet.xlsx', usecols=['First Name', 'Last Name', 'City'])
single

  First Name Last Name           City
0    Brandon     James          Miami
1       Sean   Hawkins         Denver
2       Judy       Day    Los Angeles
3     Ashley      Ruiz  San Francisco
4  Stephanie     Gomez       Portland

In [36]:
single = pd.read_excel('data/Single Worksheet.xlsx', usecols=['First Name', 'Last Name', 'City'],index_col='City')
single

              First Name Last Name
City
Miami            Brandon     James
Denver              Sean   Hawkins
Los Angeles         Judy       Day
San Francisco     Ashley      Ruiz
Portland       Stephanie     Gomez

In [40]:
single = pd.read_excel('data/Single Worksheet.xlsx', usecols=['First Name', 'Last Name', 'City'], index_col=2)
single

              First Name Last Name
City
Miami            Brandon     James
Denver              Sean   Hawkins
Los Angeles         Judy       Day
San Francisco     Ashley      Ruiz
Portland       Stephanie     Gomez

In [41]:
multiple = pd.read_excel('data/Multiple Worksheets.xlsx')
multiple

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [42]:
multiple = pd.read_excel('data/Multiple Worksheets.xlsx',sheet_name=0)
multiple

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [43]:
multiple = pd.read_excel('data/Multiple Worksheets.xlsx',sheet_name=1)
multiple

  First Name Last Name           City Gender
0     Parker     Power        Raleigh      F
1    Preston  Prescott   Philadelphia      F
2    Ronaldo   Donaldo         Bangor      M
3      Megan   Stiller  San Francisco      M
4     Bustin    Jieber         Austin      F

In [44]:
multiple = pd.read_excel('data/Multiple Worksheets.xlsx',sheet_name=2)
multiple

  First Name  Last Name     City Gender
0     Robert     Miller  Seattle      M
1       Tara     Garcia  Phoenix      F
2    Raphael  Rodriguez  Orlando      M

In [46]:
multiple = pd.read_excel('data/Multiple Worksheets.xlsx',sheet_name="Data 1")
multiple

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [47]:
multiple = pd.read_excel('data/Multiple Worksheets.xlsx',sheet_name="Data 2")
multiple

  First Name Last Name           City Gender
0     Parker     Power        Raleigh      F
1    Preston  Prescott   Philadelphia      F
2    Ronaldo   Donaldo         Bangor      M
3      Megan   Stiller  San Francisco      M
4     Bustin    Jieber         Austin      F

In [48]:
multiple = pd.read_excel('data/Multiple Worksheets.xlsx',sheet_name="Data 3")
multiple

  First Name  Last Name     City Gender
0     Robert     Miller  Seattle      M
1       Tara     Garcia  Phoenix      F
2    Raphael  Rodriguez  Orlando      M

In [49]:
multiple = pd.read_excel('data/Multiple Worksheets.xlsx',sheet_name=None)
multiple

{'Data 1':   First Name Last Name           City Gender
 0    Brandon     James          Miami      M
 1       Sean   Hawkins         Denver      M
 2       Judy       Day    Los Angeles      F
 3     Ashley      Ruiz  San Francisco      F
 4  Stephanie     Gomez       Portland      F,
 'Data 2':   First Name Last Name           City Gender
 0     Parker     Power        Raleigh      F
 1    Preston  Prescott   Philadelphia      F
 2    Ronaldo   Donaldo         Bangor      M
 3      Megan   Stiller  San Francisco      M
 4     Bustin    Jieber         Austin      F,
 'Data 3':   First Name  Last Name     City Gender
 0     Robert     Miller  Seattle      M
 1       Tara     Garcia  Phoenix      F
 2    Raphael  Rodriguez  Orlando      M}

In [50]:
type(multiple)

dict

In [51]:
baby = pd.read_csv('data/Popular_Baby_Names.csv')
baby

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank
0,2011,FEMALE,HISPANIC,GERALDINE,13,75
1,2011,FEMALE,HISPANIC,GIA,21,67
2,2011,FEMALE,HISPANIC,GIANNA,49,42
3,2011,FEMALE,HISPANIC,GISELLE,38,51
4,2011,FEMALE,HISPANIC,GRACE,36,53
...,...,...,...,...,...,...
49504,2018,FEMALE,BLACK NON HISPANIC,Nala,10,40
49505,2018,FEMALE,BLACK NON HISPANIC,Royalty,10,40
49506,2018,FEMALE,BLACK NON HISPANIC,Sariyah,10,40
49507,2018,FEMALE,BLACK NON HISPANIC,Simone,10,40
49508,2018,FEMALE,BLACK NON HISPANIC,Zahra,10,40

In [54]:
girls = baby[baby['Gender'] == 'FEMALE']
girls

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank
0,2011,FEMALE,HISPANIC,GERALDINE,13,75
1,2011,FEMALE,HISPANIC,GIA,21,67
2,2011,FEMALE,HISPANIC,GIANNA,49,42
3,2011,FEMALE,HISPANIC,GISELLE,38,51
4,2011,FEMALE,HISPANIC,GRACE,36,53
...,...,...,...,...,...,...
49504,2018,FEMALE,BLACK NON HISPANIC,Nala,10,40
49505,2018,FEMALE,BLACK NON HISPANIC,Royalty,10,40
49506,2018,FEMALE,BLACK NON HISPANIC,Sariyah,10,40
49507,2018,FEMALE,BLACK NON HISPANIC,Simone,10,40
49508,2018,FEMALE,BLACK NON HISPANIC,Zahra,10,40

In [55]:
boys = baby[baby['Gender'] == 'MALE']
boys

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank
363,2013,MALE,HISPANIC,Jared,25,80
416,2013,MALE,HISPANIC,Jariel,25,80
547,2011,MALE,ASIAN AND PACIFIC ISLANDER,AARAV,15,51
548,2011,MALE,ASIAN AND PACIFIC ISLANDER,AARON,51,19
549,2011,MALE,ASIAN AND PACIFIC ISLANDER,ABDUL,20,46
...,...,...,...,...,...,...
49336,2018,MALE,BLACK NON HISPANIC,Myles,10,51
49337,2018,MALE,BLACK NON HISPANIC,Quincy,10,51
49338,2018,MALE,BLACK NON HISPANIC,Sage,10,51
49339,2018,MALE,BLACK NON HISPANIC,Sean,10,51
49340,2018,MALE,BLACK NON HISPANIC,Seth,10,51

In [56]:
with pd.ExcelWriter('data/new_baby.xlsx') as writer:
    girls.to_excel(writer, index=False,sheet_name='girls')
    boys.to_excel(writer, index=False,sheet_name='boys')