In [1]:
import pandas as pd

In [7]:
foods = [
    ("Fruit", "Apple"),
    ("Fruit", "Banana"),
    ("Vegetable", "Broccoli"),
    ("Vegetable", "Tomato"),
]
data = [
    (3, 200, 95),
    (2, 130, 105),
    (5, 230, 22),
    (7, 310, 50)
]

mi = pd.MultiIndex.from_tuples(foods, names=["Group", "Item"])
mi

MultiIndex([(    'Fruit',    'Apple'),
            (    'Fruit',   'Banana'),
            ('Vegetable', 'Broccoli'),
            ('Vegetable',   'Tomato')],
           names=['Group', 'Item'])

In [10]:
store = pd.DataFrame(data, index=mi, columns=["Price", "Weight", "Calory"])
store

                    Price  Weight  Calory
Group     Item
Fruit     Apple         3     200      95
          Banana        2     130     105
Vegetable Broccoli      5     230      22
          Tomato        7     310      50

In [12]:
store.index

MultiIndex([(    'Fruit',    'Apple'),
            (    'Fruit',   'Banana'),
            ('Vegetable', 'Broccoli'),
            ('Vegetable',   'Tomato')],
           names=['Group', 'Item'])

In [14]:
mv = pd.read_csv('data/movies.csv', index_col=0)
mv

                             Title           Studio       Gross  Year
Rank
1                Avengers: Endgame      Buena Vista  $2,796.30   2019
2                           Avatar              Fox  $2,789.70   2009
3                          Titanic        Paramount  $2,187.50   1997
4     Star Wars: The Force Awakens      Buena Vista  $2,068.20   2015
5           Avengers: Infinity War      Buena Vista  $2,048.40   2018
...                            ...              ...         ...   ...
778                      Yogi Bear  Warner Brothers    $201.60   2010
779            Garfield: The Movie              Fox    $200.80   2004
780                    Cats & Dogs  Warner Brothers    $200.70   2001
781       The Hunt for Red October        Paramount    $200.50   1990
782                       Valkyrie              MGM    $200.30   2008

[782 rows x 4 columns]

In [15]:
mv.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       773, 774, 775, 776, 777, 778, 779, 780, 781, 782],
      dtype='int64', name='Rank', length=782)

In [16]:
mv = pd.read_csv('data/movies.csv', index_col=[0, 1])
mv

                                            Studio       Gross  Year
Rank Title
1    Avengers: Endgame                 Buena Vista  $2,796.30   2019
2    Avatar                                    Fox  $2,789.70   2009
3    Titanic                             Paramount  $2,187.50   1997
4    Star Wars: The Force Awakens      Buena Vista  $2,068.20   2015
5    Avengers: Infinity War            Buena Vista  $2,048.40   2018
...                                            ...         ...   ...
778  Yogi Bear                     Warner Brothers    $201.60   2010
779  Garfield: The Movie                       Fox    $200.80   2004
780  Cats & Dogs                   Warner Brothers    $200.70   2001
781  The Hunt for Red October            Paramount    $200.50   1990
782  Valkyrie                                  MGM    $200.30   2008

[782 rows x 3 columns]

In [17]:
mv.index

MultiIndex([(  1,            'Avengers: Endgame'),
            (  2,                       'Avatar'),
            (  3,                      'Titanic'),
            (  4, 'Star Wars: The Force Awakens'),
            (  5,       'Avengers: Infinity War'),
            (  6,               'Jurassic World'),
            (  7,        'Marvel's The Avengers'),
            (  8,                    'Furious 7'),
            (  9,      'Avengers: Age of Ultron'),
            ( 10,                'Black Panther'),
            ...
            (773,       'Fun with Dick and Jane'),
            (774, 'Teenage Mutant Ninja Turtles'),
            (775,             'Kindergarten Cop'),
            (776,       'Straight Outta Compton'),
            (777,               '21 Jump Street'),
            (778,                    'Yogi Bear'),
            (779,          'Garfield: The Movie'),
            (780,                  'Cats & Dogs'),
            (781,     'The Hunt for Red October'),
            (782,                     'Valkyrie')],
           names=['Rank', 'Title'], length=782)

In [20]:
nb = pd.read_csv('data/neighborhoods.csv')
nb

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Culture,Culture.1,Services,Services.1
0,NaN,NaN,NaN,Restaurants,Museums,Police,Schools
1,State,City,Street,NaN,NaN,NaN,NaN
2,MO,Fisherborough,244 Tracy View,C+,F,D-,A+
3,SD,Port Curtisville,446 Cynthia Inlet,C-,B,B,D+
4,WV,Jimenezview,432 John Common,A,A+,F,B
...,...,...,...,...,...,...,...
248,MI,North Matthew,055 Clayton Isle,B-,C,B,C+
249,MT,Chadton,601 Richards Road,A-,D,D+,D
250,SC,Diazmouth,385 Robin Harbors,F,D,B-,D+
251,VA,Laurentown,255 Gonzalez Land,C+,B-,F,D-
252,NE,South Kennethmouth,346 Wallace Pass,C-,B-,A,A-

In [21]:
nb = pd.read_csv('data/neighborhoods.csv', index_col=[0, 1, 2])
nb

,,,Culture,Culture.1,Services,Services.1
NaN,NaN,NaN,Restaurants,Museums,Police,Schools
State,City,Street,NaN,NaN,NaN,NaN
MO,Fisherborough,244 Tracy View,C+,F,D-,A+
SD,Port Curtisville,446 Cynthia Inlet,C-,B,B,D+
WV,Jimenezview,432 John Common,A,A+,F,B
...,...,...,...,...,...,...
MI,North Matthew,055 Clayton Isle,B-,C,B,C+
MT,Chadton,601 Richards Road,A-,D,D+,D
SC,Diazmouth,385 Robin Harbors,F,D,B-,D+
VA,Laurentown,255 Gonzalez Land,C+,B-,F,D-
NE,South Kennethmouth,346 Wallace Pass,C-,B-,A,A-

In [23]:
nb = pd.read_csv('data/neighborhoods.csv', index_col=[0, 1, 2], header=0)
nb

,,,Culture,Culture.1,Services,Services.1
NaN,NaN,NaN,Restaurants,Museums,Police,Schools
State,City,Street,NaN,NaN,NaN,NaN
MO,Fisherborough,244 Tracy View,C+,F,D-,A+
SD,Port Curtisville,446 Cynthia Inlet,C-,B,B,D+
WV,Jimenezview,432 John Common,A,A+,F,B
...,...,...,...,...,...,...
MI,North Matthew,055 Clayton Isle,B-,C,B,C+
MT,Chadton,601 Richards Road,A-,D,D+,D
SC,Diazmouth,385 Robin Harbors,F,D,B-,D+
VA,Laurentown,255 Gonzalez Land,C+,B-,F,D-
NE,South Kennethmouth,346 Wallace Pass,C-,B-,A,A-

In [24]:
nb = pd.read_csv('data/neighborhoods.csv', index_col=[0, 1, 2], header=1)
nb

                                           Restaurants Museums Police Schools
State City               Street                    NaN     NaN    NaN     NaN
MO    Fisherborough      244 Tracy View             C+       F     D-      A+
SD    Port Curtisville   446 Cynthia Inlet          C-       B      B      D+
WV    Jimenezview        432 John Common             A      A+      F       B
AK    Stevenshire        238 Andrew Rue             D-       A     A-      A-
...                                                ...     ...    ...     ...
MI    North Matthew      055 Clayton Isle           B-       C      B      C+
MT    Chadton            601 Richards Road          A-       D     D+       D
SC    Diazmouth          385 Robin Harbors           F       D     B-      D+
VA    Laurentown         255 Gonzalez Land          C+      B-      F      D-
NE    South Kennethmouth 346 Wallace Pass           C-      B-      A      A-

[252 rows x 4 columns]

In [26]:
nb = pd.read_csv('data/neighborhoods.csv', index_col=[0, 1, 2], header=[0, 1])
nb

                                               Culture         Services  \
                                           Restaurants Museums   Police
State City               Street
MO    Fisherborough      244 Tracy View             C+       F       D-
SD    Port Curtisville   446 Cynthia Inlet          C-       B        B
WV    Jimenezview        432 John Common             A      A+        F
AK    Stevenshire        238 Andrew Rue             D-       A       A-
ND    New Joshuaport     877 Walter Neck            D+      C-        B
...                                                ...     ...      ...
MI    North Matthew      055 Clayton Isle           B-       C        B
MT    Chadton            601 Richards Road          A-       D       D+
SC    Diazmouth          385 Robin Harbors           F       D       B-
VA    Laurentown         255 Gonzalez Land          C+      B-        F
NE    South Kennethmouth 346 Wallace Pass           C-      B-        A


                                           Schools
State City               Street
MO    Fisherborough      244 Tracy View         A+
SD    Port Curtisville   446 Cynthia Inlet      D+
WV    Jimenezview        432 John Common         B
AK    Stevenshire        238 Andrew Rue         A-
ND    New Joshuaport     877 Walter Neck         B
...                                            ...
MI    North Matthew      055 Clayton Isle       C+
MT    Chadton            601 Richards Road       D
SC    Diazmouth          385 Robin Harbors      D+
VA    Laurentown         255 Gonzalez Land      D-
NE    South Kennethmouth 346 Wallace Pass       A-

[251 rows x 4 columns]

In [27]:
nb.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 251 entries, ('MO', 'Fisherborough', '244 Tracy View') to ('NE', 'South Kennethmouth', '346 Wallace Pass')
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   (Culture, Restaurants)  251 non-null    object
 1   (Culture, Museums)      251 non-null    object
 2   (Services, Police)      251 non-null    object
 3   (Services, Schools)     251 non-null    object
dtypes: object(4)
memory usage: 27.1+ KB

In [28]:
nb.index

MultiIndex([('MO',      'Fisherborough',        '244 Tracy View'),
            ('SD',   'Port Curtisville',     '446 Cynthia Inlet'),
            ('WV',        'Jimenezview',       '432 John Common'),
            ('AK',        'Stevenshire',        '238 Andrew Rue'),
            ('ND',     'New Joshuaport',       '877 Walter Neck'),
            ('ID',         'Wellsville',   '696 Weber Stravenue'),
            ('TN',          'Jodiburgh',    '285 Justin Corners'),
            ('DC',   'Lake Christopher',   '607 Montoya Harbors'),
            ('OH',          'Port Mike',      '041 Michael Neck'),
            ('ND',         'Hardyburgh', '550 Gilmore Mountains'),
            ...
            ('AK',          'Scottstad',      '114 Jones Garden'),
            ('IA',    'Port Willieport',  '320 Jennifer Mission'),
            ('ME',         'Port Linda',        '692 Hill Glens'),
            ('KS',         'Kaylamouth',       '483 Freeman Via'),
            ('WA',     'Port Shawnfort',    '691 Winters Bridge'),
            ('MI',      'North Matthew',      '055 Clayton Isle'),
            ('MT',            'Chadton',     '601 Richards Road'),
            ('SC',          'Diazmouth',     '385 Robin Harbors'),
            ('VA',         'Laurentown',     '255 Gonzalez Land'),
            ('NE', 'South Kennethmouth',      '346 Wallace Pass')],
           names=['State', 'City', 'Street'], length=251)

In [30]:
nb.index.names

FrozenList(['State', 'City', 'Street'])

In [31]:
nb.index.get_level_values('City')

Index(['Fisherborough', 'Port Curtisville', 'Jimenezview', 'Stevenshire',
       'New Joshuaport', 'Wellsville', 'Jodiburgh', 'Lake Christopher',
       'Port Mike', 'Hardyburgh',
       ...
       'Scottstad', 'Port Willieport', 'Port Linda', 'Kaylamouth',
       'Port Shawnfort', 'North Matthew', 'Chadton', 'Diazmouth', 'Laurentown',
       'South Kennethmouth'],
      dtype='object', name='City', length=251)

In [33]:
nb.index.get_level_values('State')

Index(['MO', 'SD', 'WV', 'AK', 'ND', 'ID', 'TN', 'DC', 'OH', 'ND',
       ...
       'AK', 'IA', 'ME', 'KS', 'WA', 'MI', 'MT', 'SC', 'VA', 'NE'],
      dtype='object', name='State', length=251)

In [36]:
nb.index.get_level_values('State').nunique()

50

In [37]:
nb.index.get_level_values('State').value_counts()

State
ME    10
DE     9
SC     9
ND     8
HI     8
NY     8
AL     8
ID     7
NV     7
OK     7
VT     7
WV     7
MN     6
IN     6
DC     6
PA     6
UT     6
MO     6
MT     6
WY     6
IA     5
NC     5
OH     5
TN     5
RI     5
NH     5
GA     5
KS     5
FL     5
AK     4
CT     4
AR     4
NE     4
MI     4
MS     4
MD     3
SD     3
VA     3
NM     3
OR     3
CA     3
TX     3
CO     3
AZ     3
MA     3
LA     3
WI     2
KY     2
NJ     1
WA     1
Name: count, dtype: int64

In [38]:
nb.columns

MultiIndex([( 'Culture', 'Restaurants'),
            ( 'Culture',     'Museums'),
            ('Services',      'Police'),
            ('Services',     'Schools')],
           )

In [40]:
nb.columns.names = ['Category', 'SubCategory']
nb

Category                                       Culture         Services  \
SubCategory                                Restaurants Museums   Police
State City               Street
MO    Fisherborough      244 Tracy View             C+       F       D-
SD    Port Curtisville   446 Cynthia Inlet          C-       B        B
WV    Jimenezview        432 John Common             A      A+        F
AK    Stevenshire        238 Andrew Rue             D-       A       A-
ND    New Joshuaport     877 Walter Neck            D+      C-        B
...                                                ...     ...      ...
MI    North Matthew      055 Clayton Isle           B-       C        B
MT    Chadton            601 Richards Road          A-       D       D+
SC    Diazmouth          385 Robin Harbors           F       D       B-
VA    Laurentown         255 Gonzalez Land          C+      B-        F
NE    South Kennethmouth 346 Wallace Pass           C-      B-        A

Category
SubCategory                                Schools
State City               Street
MO    Fisherborough      244 Tracy View         A+
SD    Port Curtisville   446 Cynthia Inlet      D+
WV    Jimenezview        432 John Common         B
AK    Stevenshire        238 Andrew Rue         A-
ND    New Joshuaport     877 Walter Neck         B
...                                            ...
MI    North Matthew      055 Clayton Isle       C+
MT    Chadton            601 Richards Road       D
SC    Diazmouth          385 Robin Harbors      D+
VA    Laurentown         255 Gonzalez Land      D-
NE    South Kennethmouth 346 Wallace Pass       A-

[251 rows x 4 columns]

In [41]:
nb.columns

MultiIndex([( 'Culture', 'Restaurants'),
            ( 'Culture',     'Museums'),
            ('Services',      'Police'),
            ('Services',     'Schools')],
           names=['Category', 'SubCategory'])

In [42]:
nb.columns.names

FrozenList(['Category', 'SubCategory'])

In [43]:
nb.columns.get_level_values('Category')

Index(['Culture', 'Culture', 'Services', 'Services'], dtype='object', name='Category')

In [45]:
nb.sort_index()

Category                                      Culture         Services
SubCategory                               Restaurants Museums   Police Schools
State City           Street
AK    Rowlandchester 386 Rebecca Cove              C-      A-       A+       C
      Scottstad      082 Leblanc Freeway            D      C-        D      B+
                     114 Jones Garden              D-      D-        D       D
      Stevenshire    238 Andrew Rue                D-       A       A-      A-
AL    Clarkland      430 Douglas Mission            A       F       C+      B+
...                                               ...     ...      ...     ...
WY    Lake Nicole    754 Weaver Turnpike            B      D-        B       D
                     933 Jennifer Burg              C      A+       A-       C
      Martintown     013 Bell Mills                C-       D       A-      B-
      Port Jason     624 Faulkner Orchard          A-       F       C+      C+
      Reneeshire     717 Patel Square               B      B+        D       A

[251 rows x 4 columns]

In [46]:
nb.sort_index(ascending=False)

Category                                      Culture         Services
SubCategory                               Restaurants Museums   Police Schools
State City           Street
WY    Reneeshire     717 Patel Square               B      B+        D       A
      Port Jason     624 Faulkner Orchard          A-       F       C+      C+
      Martintown     013 Bell Mills                C-       D       A-      B-
      Lake Nicole    933 Jennifer Burg              C      A+       A-       C
                     754 Weaver Turnpike            B      D-        B       D
...                                               ...     ...      ...     ...
AL    Clarkland      430 Douglas Mission            A       F       C+      B+
AK    Stevenshire    238 Andrew Rue                D-       A       A-      A-
      Scottstad      114 Jones Garden              D-      D-        D       D
                     082 Leblanc Freeway            D      C-        D      B+
      Rowlandchester 386 Rebecca Cove              C-      A-       A+       C

[251 rows x 4 columns]

In [47]:
nb.sort_index(ascending=[True, False, True])

Category                                      Culture         Services
SubCategory                               Restaurants Museums   Police Schools
State City           Street
AK    Stevenshire    238 Andrew Rue                D-       A       A-      A-
      Scottstad      082 Leblanc Freeway            D      C-        D      B+
                     114 Jones Garden              D-      D-        D       D
      Rowlandchester 386 Rebecca Cove              C-      A-       A+       C
AL    Vegaside       191 Mindy Meadows             B+      A-       A+      D+
...                                               ...     ...      ...     ...
WY    Port Jason     624 Faulkner Orchard          A-       F       C+      C+
      Martintown     013 Bell Mills                C-       D       A-      B-
      Lake Nicole    754 Weaver Turnpike            B      D-        B       D
                     933 Jennifer Burg              C      A+       A-       C
      Hardyburgh     227 Andrew Parkway             D      C-       D-       C

[251 rows x 4 columns]

In [48]:
nb.sort_index(level=['City', 'State'])

Category                                      Culture         Services
SubCategory                               Restaurants Museums   Police Schools
State City          Street
AR    Allisonland   124 Diaz Brooks                C-      A+        F      C+
GA    Amyburgh      941 Brian Expressway            B       B       D-      C+
IA    Amyburgh      163 Heather Neck                F       D       A+      A-
ID    Andrewshire   952 Ellis Drive                C+      A-       C+       A
UT    Baileyfort    919 Stewart Hills              D+      C+        A       C
...                                               ...     ...      ...     ...
NC    West Scott    348 Jack Branch                A-      D-       A-       A
SD    West Scott    139 Hardy Vista                C+      A-       D+      B-
IN    Wilsonborough 066 Carr Road                  A+      C-        B       F
NC    Wilsonshire   871 Christopher Vista          B+       B       D+       F
NV    Wilsonshire   542 Jessica Stream              A      A+       C-      C+

[251 rows x 4 columns]

In [50]:
nb.sort_index(level=['City', 'State'], ascending=[True, False])

Category                                      Culture         Services
SubCategory                               Restaurants Museums   Police Schools
State City          Street
AR    Allisonland   124 Diaz Brooks                C-      A+        F      C+
IA    Amyburgh      163 Heather Neck                F       D       A+      A-
GA    Amyburgh      941 Brian Expressway            B       B       D-      C+
ID    Andrewshire   952 Ellis Drive                C+      A-       C+       A
VT    Baileyfort    831 Norma Cove                  B      D+       A+      D+
...                                               ...     ...      ...     ...
SD    West Scott    139 Hardy Vista                C+      A-       D+      B-
NC    West Scott    348 Jack Branch                A-      D-       A-       A
IN    Wilsonborough 066 Carr Road                  A+      C-        B       F
NV    Wilsonshire   542 Jessica Stream              A      A+       C-      C+
NC    Wilsonshire   871 Christopher Vista          B+       B       D+       F

[251 rows x 4 columns]

In [51]:
nb.sort_index(axis=1)

Category                                   Culture             Services  \
SubCategory                                Museums Restaurants   Police
State City               Street
MO    Fisherborough      244 Tracy View          F          C+       D-
SD    Port Curtisville   446 Cynthia Inlet       B          C-        B
WV    Jimenezview        432 John Common        A+           A        F
AK    Stevenshire        238 Andrew Rue          A          D-       A-
ND    New Joshuaport     877 Walter Neck        C-          D+        B
...                                            ...         ...      ...
MI    North Matthew      055 Clayton Isle        C          B-        B
MT    Chadton            601 Richards Road       D          A-       D+
SC    Diazmouth          385 Robin Harbors       D           F       B-
VA    Laurentown         255 Gonzalez Land      B-          C+        F
NE    South Kennethmouth 346 Wallace Pass       B-          C-        A

Category
SubCategory                                Schools
State City               Street
MO    Fisherborough      244 Tracy View         A+
SD    Port Curtisville   446 Cynthia Inlet      D+
WV    Jimenezview        432 John Common         B
AK    Stevenshire        238 Andrew Rue         A-
ND    New Joshuaport     877 Walter Neck         B
...                                            ...
MI    North Matthew      055 Clayton Isle       C+
MT    Chadton            601 Richards Road       D
SC    Diazmouth          385 Robin Harbors      D+
VA    Laurentown         255 Gonzalez Land      D-
NE    South Kennethmouth 346 Wallace Pass       A-

[251 rows x 4 columns]

In [52]:
nb.sort_index(axis='columns')

Category                                   Culture             Services  \
SubCategory                                Museums Restaurants   Police
State City               Street
MO    Fisherborough      244 Tracy View          F          C+       D-
SD    Port Curtisville   446 Cynthia Inlet       B          C-        B
WV    Jimenezview        432 John Common        A+           A        F
AK    Stevenshire        238 Andrew Rue          A          D-       A-
ND    New Joshuaport     877 Walter Neck        C-          D+        B
...                                            ...         ...      ...
MI    North Matthew      055 Clayton Isle        C          B-        B
MT    Chadton            601 Richards Road       D          A-       D+
SC    Diazmouth          385 Robin Harbors       D           F       B-
VA    Laurentown         255 Gonzalez Land      B-          C+        F
NE    South Kennethmouth 346 Wallace Pass       B-          C-        A

Category
SubCategory                                Schools
State City               Street
MO    Fisherborough      244 Tracy View         A+
SD    Port Curtisville   446 Cynthia Inlet      D+
WV    Jimenezview        432 John Common         B
AK    Stevenshire        238 Andrew Rue         A-
ND    New Joshuaport     877 Walter Neck         B
...                                            ...
MI    North Matthew      055 Clayton Isle       C+
MT    Chadton            601 Richards Road       D
SC    Diazmouth          385 Robin Harbors      D+
VA    Laurentown         255 Gonzalez Land      D-
NE    South Kennethmouth 346 Wallace Pass       A-

[251 rows x 4 columns]

In [56]:
nb.sort_index(axis='columns', level=['SubCategory'], ascending=False)

,,Category,Services,Culture,Services,Culture
,,SubCategory,Schools,Restaurants,Police,Museums
State,City,Street,,,,
MO,Fisherborough,244 Tracy View,A+,C+,D-,F
SD,Port Curtisville,446 Cynthia Inlet,D+,C-,B,B
WV,Jimenezview,432 John Common,B,A,F,A+
AK,Stevenshire,238 Andrew Rue,A-,D-,A-,A
ND,New Joshuaport,877 Walter Neck,B,D+,B,C-
...,...,...,...,...,...,...
MI,North Matthew,055 Clayton Isle,C+,B-,B,C
MT,Chadton,601 Richards Road,D,A-,D+,D
SC,Diazmouth,385 Robin Harbors,D+,F,B-,D
VA,Laurentown,255 Gonzalez Land,D-,C+,F,B-
NE,South Kennethmouth,346 Wallace Pass,A-,C-,A,B-

In [57]:
nb['Services']

SubCategory                                Police Schools
State City               Street
MO    Fisherborough      244 Tracy View        D-      A+
SD    Port Curtisville   446 Cynthia Inlet      B      D+
WV    Jimenezview        432 John Common        F       B
AK    Stevenshire        238 Andrew Rue        A-      A-
ND    New Joshuaport     877 Walter Neck        B       B
...                                           ...     ...
MI    North Matthew      055 Clayton Isle       B      C+
MT    Chadton            601 Richards Road     D+       D
SC    Diazmouth          385 Robin Harbors     B-      D+
VA    Laurentown         255 Gonzalez Land      F      D-
NE    South Kennethmouth 346 Wallace Pass       A      A-

[251 rows x 2 columns]

In [62]:
nb[[('Services', "Police"), ('Culture', 'Museums')]]

Category                                   Services Culture
SubCategory                                  Police Museums
State City               Street
MO    Fisherborough      244 Tracy View          D-       F
SD    Port Curtisville   446 Cynthia Inlet        B       B
WV    Jimenezview        432 John Common          F      A+
AK    Stevenshire        238 Andrew Rue          A-       A
ND    New Joshuaport     877 Walter Neck          B      C-
...                                             ...     ...
MI    North Matthew      055 Clayton Isle         B       C
MT    Chadton            601 Richards Road       D+       D
SC    Diazmouth          385 Robin Harbors       B-       D
VA    Laurentown         255 Gonzalez Land        F      B-
NE    South Kennethmouth 346 Wallace Pass         A      B-

[251 rows x 2 columns]

In [64]:
nb.loc[('NY', 'Chadburgh')]

C:\Users\mahdi\AppData\Local\Temp\ipykernel_24308\662658637.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  nb.loc[('NY','Chadburgh')]

Category               Culture         Services
SubCategory        Restaurants Museums   Police Schools
Street
857 Michelle Shoal          B+      C-       D+      C-

In [66]:
nb = nb.sort_index()
nb.loc[('NY', 'Chadburgh')]

Category               Culture         Services
SubCategory        Restaurants Museums   Police Schools
Street
857 Michelle Shoal          B+      C-       D+      C-

In [67]:
nb.loc[('NY', 'Culture')]

SubCategory                               Restaurants Museums
City                 Street
Chadburgh            857 Michelle Shoal            B+      C-
Lake Christopher     811 Kathleen Trace            B+       D
Lake Laurenhaven     735 Loretta Mills              B      A+
Lake Timothy         398 Erika Lake                C+      B-
New Joshuaport       160 Martin River               C       C
Port Elizabeth       804 Stephanie Summit           C      D-
Reneeshire           436 Parker Shore              A-      D-
West Christophertown 007 Macias Points              D      A-

In [69]:
nb.loc['NY', 'Culture']

SubCategory                               Restaurants Museums
City                 Street
Chadburgh            857 Michelle Shoal            B+      C-
Lake Christopher     811 Kathleen Trace            B+       D
Lake Laurenhaven     735 Loretta Mills              B      A+
Lake Timothy         398 Erika Lake                C+      B-
New Joshuaport       160 Martin River               C       C
Port Elizabeth       804 Stephanie Summit           C      D-
Reneeshire           436 Parker Shore              A-      D-
West Christophertown 007 Macias Points              D      A-

In [70]:
nb.loc[('NY',), ('Culture',)]

SubCategory                               Restaurants Museums
City                 Street
Chadburgh            857 Michelle Shoal            B+      C-
Lake Christopher     811 Kathleen Trace            B+       D
Lake Laurenhaven     735 Loretta Mills              B      A+
Lake Timothy         398 Erika Lake                C+      B-
New Joshuaport       160 Martin River               C       C
Port Elizabeth       804 Stephanie Summit           C      D-
Reneeshire           436 Parker Shore              A-      D-
West Christophertown 007 Macias Points              D      A-

In [72]:
nb

Category                                      Culture         Services
SubCategory                               Restaurants Museums   Police Schools
State City           Street
AK    Rowlandchester 386 Rebecca Cove              C-      A-       A+       C
      Scottstad      082 Leblanc Freeway            D      C-        D      B+
                     114 Jones Garden              D-      D-        D       D
      Stevenshire    238 Andrew Rue                D-       A       A-      A-
AL    Clarkland      430 Douglas Mission            A       F       C+      B+
...                                               ...     ...      ...     ...
WY    Lake Nicole    754 Weaver Turnpike            B      D-        B       D
                     933 Jennifer Burg              C      A+       A-       C
      Martintown     013 Bell Mills                C-       D       A-      B-
      Port Jason     624 Faulkner Orchard          A-       F       C+      C+
      Reneeshire     717 Patel Square               B      B+        D       A

[251 rows x 4 columns]

In [73]:
nb.iloc[0,0]

'C-'

In [75]:
nb.xs(key='114 Jones Garden',level=2)

Category            Culture         Services
SubCategory     Restaurants Museums   Police Schools
State City
AK    Scottstad          D-      D-        D       D

In [76]:
nb.xs(key='114 Jones Garden',level='Street')

Category            Culture         Services
SubCategory     Restaurants Museums   Police Schools
State City
AK    Scottstad          D-      D-        D       D

In [82]:
nb.xs(axis=1,key='Museums',level='SubCategory')

Category                                  Culture
State City           Street
AK    Rowlandchester 386 Rebecca Cove          A-
      Scottstad      082 Leblanc Freeway       C-
                     114 Jones Garden          D-
      Stevenshire    238 Andrew Rue             A
AL    Clarkland      430 Douglas Mission        F
...                                           ...
WY    Lake Nicole    754 Weaver Turnpike       D-
                     933 Jennifer Burg         A+
      Martintown     013 Bell Mills             D
      Port Jason     624 Faulkner Orchard       F
      Reneeshire     717 Patel Square          B+

[251 rows x 1 columns]

In [83]:
nb.xs(key=('AK','238 Andrew Rue'),level=[0,2])

Category        Culture         Services
SubCategory Restaurants Museums   Police Schools
City
Stevenshire          D-       A       A-      A-

In [84]:
nb

Category                                      Culture         Services
SubCategory                               Restaurants Museums   Police Schools
State City           Street
AK    Rowlandchester 386 Rebecca Cove              C-      A-       A+       C
      Scottstad      082 Leblanc Freeway            D      C-        D      B+
                     114 Jones Garden              D-      D-        D       D
      Stevenshire    238 Andrew Rue                D-       A       A-      A-
AL    Clarkland      430 Douglas Mission            A       F       C+      B+
...                                               ...     ...      ...     ...
WY    Lake Nicole    754 Weaver Turnpike            B      D-        B       D
                     933 Jennifer Burg              C      A+       A-       C
      Martintown     013 Bell Mills                C-       D       A-      B-
      Port Jason     624 Faulkner Orchard          A-       F       C+      C+
      Reneeshire     717 Patel Square               B      B+        D       A

[251 rows x 4 columns]

In [85]:
nb.reorder_levels(order=['City', 'State','Street'])

Category                                      Culture         Services
SubCategory                               Restaurants Museums   Police Schools
City           State Street
Rowlandchester AK    386 Rebecca Cove              C-      A-       A+       C
Scottstad      AK    082 Leblanc Freeway            D      C-        D      B+
                     114 Jones Garden              D-      D-        D       D
Stevenshire    AK    238 Andrew Rue                D-       A       A-      A-
Clarkland      AL    430 Douglas Mission            A       F       C+      B+
...                                               ...     ...      ...     ...
Lake Nicole    WY    754 Weaver Turnpike            B      D-        B       D
                     933 Jennifer Burg              C      A+       A-       C
Martintown     WY    013 Bell Mills                C-       D       A-      B-
Port Jason     WY    624 Faulkner Orchard          A-       F       C+      C+
Reneeshire     WY    717 Patel Square               B      B+        D       A

[251 rows x 4 columns]

In [86]:
nb.reorder_levels(order=[1,0,2])

Category                                      Culture         Services
SubCategory                               Restaurants Museums   Police Schools
City           State Street
Rowlandchester AK    386 Rebecca Cove              C-      A-       A+       C
Scottstad      AK    082 Leblanc Freeway            D      C-        D      B+
                     114 Jones Garden              D-      D-        D       D
Stevenshire    AK    238 Andrew Rue                D-       A       A-      A-
Clarkland      AL    430 Douglas Mission            A       F       C+      B+
...                                               ...     ...      ...     ...
Lake Nicole    WY    754 Weaver Turnpike            B      D-        B       D
                     933 Jennifer Burg              C      A+       A-       C
Martintown     WY    013 Bell Mills                C-       D       A-      B-
Port Jason     WY    624 Faulkner Orchard          A-       F       C+      C+
Reneeshire     WY    717 Patel Square               B      B+        D       A

[251 rows x 4 columns]

In [87]:
nb.reset_index()

Category    State            City                Street     Culture          \
SubCategory                                             Restaurants Museums
0              AK  Rowlandchester      386 Rebecca Cove          C-      A-
1              AK       Scottstad   082 Leblanc Freeway           D      C-
2              AK       Scottstad      114 Jones Garden          D-      D-
3              AK     Stevenshire        238 Andrew Rue          D-       A
4              AL       Clarkland   430 Douglas Mission           A       F
..            ...             ...                   ...         ...     ...
246            WY     Lake Nicole   754 Weaver Turnpike           B      D-
247            WY     Lake Nicole     933 Jennifer Burg           C      A+
248            WY      Martintown        013 Bell Mills          C-       D
249            WY      Port Jason  624 Faulkner Orchard          A-       F
250            WY      Reneeshire      717 Patel Square           B      B+

Category    Services
SubCategory   Police Schools
0                 A+       C
1                  D      B+
2                  D       D
3                 A-      A-
4                 C+      B+
..               ...     ...
246                B       D
247               A-       C
248               A-      B-
249               C+      C+
250                D       A

[251 rows x 7 columns]

In [88]:
nb.reset_index(col_level='SubCategory')

Category                                                    Culture          \
SubCategory State            City                Street Restaurants Museums
0              AK  Rowlandchester      386 Rebecca Cove          C-      A-
1              AK       Scottstad   082 Leblanc Freeway           D      C-
2              AK       Scottstad      114 Jones Garden          D-      D-
3              AK     Stevenshire        238 Andrew Rue          D-       A
4              AL       Clarkland   430 Douglas Mission           A       F
..            ...             ...                   ...         ...     ...
246            WY     Lake Nicole   754 Weaver Turnpike           B      D-
247            WY     Lake Nicole     933 Jennifer Burg           C      A+
248            WY      Martintown        013 Bell Mills          C-       D
249            WY      Port Jason  624 Faulkner Orchard          A-       F
250            WY      Reneeshire      717 Patel Square           B      B+

Category    Services
SubCategory   Police Schools
0                 A+       C
1                  D      B+
2                  D       D
3                 A-      A-
4                 C+      B+
..               ...     ...
246                B       D
247               A-       C
248               A-      B-
249               C+      C+
250                D       A

[251 rows x 7 columns]

In [89]:
nb.reset_index(col_level='SubCategory',level=1)

Category                                       Culture         Services  \
SubCategory                           City Restaurants Museums   Police
State Street
AK    386 Rebecca Cove      Rowlandchester          C-      A-       A+
      082 Leblanc Freeway        Scottstad           D      C-        D
      114 Jones Garden           Scottstad          D-      D-        D
      238 Andrew Rue           Stevenshire          D-       A       A-
AL    430 Douglas Mission        Clarkland           A       F       C+
...                                    ...         ...     ...      ...
WY    754 Weaver Turnpike      Lake Nicole           B      D-        B
      933 Jennifer Burg        Lake Nicole           C      A+       A-
      013 Bell Mills            Martintown          C-       D       A-
      624 Faulkner Orchard      Port Jason          A-       F       C+
      717 Patel Square          Reneeshire           B      B+        D

Category
SubCategory                Schools
State Street
AK    386 Rebecca Cove           C
      082 Leblanc Freeway       B+
      114 Jones Garden           D
      238 Andrew Rue            A-
AL    430 Douglas Mission       B+
...                            ...
WY    754 Weaver Turnpike        D
      933 Jennifer Burg          C
      013 Bell Mills            B-
      624 Faulkner Orchard      C+
      717 Patel Square           A

[251 rows x 5 columns]

In [90]:
nb.reset_index(col_level='SubCategory',level='City')

Category                                       Culture         Services  \
SubCategory                           City Restaurants Museums   Police
State Street
AK    386 Rebecca Cove      Rowlandchester          C-      A-       A+
      082 Leblanc Freeway        Scottstad           D      C-        D
      114 Jones Garden           Scottstad          D-      D-        D
      238 Andrew Rue           Stevenshire          D-       A       A-
AL    430 Douglas Mission        Clarkland           A       F       C+
...                                    ...         ...     ...      ...
WY    754 Weaver Turnpike      Lake Nicole           B      D-        B
      933 Jennifer Burg        Lake Nicole           C      A+       A-
      013 Bell Mills            Martintown          C-       D       A-
      624 Faulkner Orchard      Port Jason          A-       F       C+
      717 Patel Square          Reneeshire           B      B+        D

Category
SubCategory                Schools
State Street
AK    386 Rebecca Cove           C
      082 Leblanc Freeway       B+
      114 Jones Garden           D
      238 Andrew Rue            A-
AL    430 Douglas Mission       B+
...                            ...
WY    754 Weaver Turnpike        D
      933 Jennifer Burg          C
      013 Bell Mills            B-
      624 Faulkner Orchard      C+
      717 Patel Square           A

[251 rows x 5 columns]

In [92]:
nb.reset_index( level=['City','State'])

Category             State            City     Culture         Services  \
SubCategory                                Restaurants Museums   Police
Street
386 Rebecca Cove        AK  Rowlandchester          C-      A-       A+
082 Leblanc Freeway     AK       Scottstad           D      C-        D
114 Jones Garden        AK       Scottstad          D-      D-        D
238 Andrew Rue          AK     Stevenshire          D-       A       A-
430 Douglas Mission     AL       Clarkland           A       F       C+
...                    ...             ...         ...     ...      ...
754 Weaver Turnpike     WY     Lake Nicole           B      D-        B
933 Jennifer Burg       WY     Lake Nicole           C      A+       A-
013 Bell Mills          WY      Martintown          C-       D       A-
624 Faulkner Orchard    WY      Port Jason          A-       F       C+
717 Patel Square        WY      Reneeshire           B      B+        D

Category
SubCategory          Schools
Street
386 Rebecca Cove           C
082 Leblanc Freeway       B+
114 Jones Garden           D
238 Andrew Rue            A-
430 Douglas Mission       B+
...                      ...
754 Weaver Turnpike        D
933 Jennifer Burg          C
013 Bell Mills            B-
624 Faulkner Orchard      C+
717 Patel Square           A

[251 rows x 6 columns]

In [93]:
nb.reset_index( level=['City','State'],drop=True)

Category                 Culture         Services
SubCategory          Restaurants Museums   Police Schools
Street
386 Rebecca Cove              C-      A-       A+       C
082 Leblanc Freeway            D      C-        D      B+
114 Jones Garden              D-      D-        D       D
238 Andrew Rue                D-       A       A-      A-
430 Douglas Mission            A       F       C+      B+
...                          ...     ...      ...     ...
754 Weaver Turnpike            B      D-        B       D
933 Jennifer Burg              C      A+       A-       C
013 Bell Mills                C-       D       A-      B-
624 Faulkner Orchard          A-       F       C+      C+
717 Patel Square               B      B+        D       A

[251 rows x 4 columns]

In [95]:
nb = nb.reset_index()
nb

Category    index State            City                Street     Culture  \
SubCategory                                                   Restaurants
0               0    AK  Rowlandchester      386 Rebecca Cove          C-
1               1    AK       Scottstad   082 Leblanc Freeway           D
2               2    AK       Scottstad      114 Jones Garden          D-
3               3    AK     Stevenshire        238 Andrew Rue          D-
4               4    AL       Clarkland   430 Douglas Mission           A
..            ...   ...             ...                   ...         ...
246           246    WY     Lake Nicole   754 Weaver Turnpike           B
247           247    WY     Lake Nicole     933 Jennifer Burg           C
248           248    WY      Martintown        013 Bell Mills          C-
249           249    WY      Port Jason  624 Faulkner Orchard          A-
250           250    WY      Reneeshire      717 Patel Square           B

Category            Services
SubCategory Museums   Police Schools
0                A-       A+       C
1                C-        D      B+
2                D-        D       D
3                 A       A-      A-
4                 F       C+      B+
..              ...      ...     ...
246              D-        B       D
247              A+       A-       C
248               D       A-      B-
249               F       C+      C+
250              B+        D       A

[251 rows x 8 columns]

In [96]:
nb.set_index(keys='City')

Category       index State                Street     Culture         Services  \
SubCategory                                      Restaurants Museums   Police
City
Rowlandchester     0    AK      386 Rebecca Cove          C-      A-       A+
Scottstad          1    AK   082 Leblanc Freeway           D      C-        D
Scottstad          2    AK      114 Jones Garden          D-      D-        D
Stevenshire        3    AK        238 Andrew Rue          D-       A       A-
Clarkland          4    AL   430 Douglas Mission           A       F       C+
...              ...   ...                   ...         ...     ...      ...
Lake Nicole      246    WY   754 Weaver Turnpike           B      D-        B
Lake Nicole      247    WY     933 Jennifer Burg           C      A+       A-
Martintown       248    WY        013 Bell Mills          C-       D       A-
Port Jason       249    WY  624 Faulkner Orchard          A-       F       C+
Reneeshire       250    WY      717 Patel Square           B      B+        D

Category
SubCategory    Schools
City
Rowlandchester       C
Scottstad           B+
Scottstad            D
Stevenshire         A-
Clarkland           B+
...                ...
Lake Nicole          D
Lake Nicole          C
Martintown          B-
Port Jason          C+
Reneeshire           A

[251 rows x 7 columns]

In [97]:
nb.set_index(keys=('Culture','Museums'))

Category           index State            City                Street  \
SubCategory
(Culture, Museums)
A-                     0    AK  Rowlandchester      386 Rebecca Cove
C-                     1    AK       Scottstad   082 Leblanc Freeway
D-                     2    AK       Scottstad      114 Jones Garden
A                      3    AK     Stevenshire        238 Andrew Rue
F                      4    AL       Clarkland   430 Douglas Mission
...                  ...   ...             ...                   ...
D-                   246    WY     Lake Nicole   754 Weaver Turnpike
A+                   247    WY     Lake Nicole     933 Jennifer Burg
D                    248    WY      Martintown        013 Bell Mills
F                    249    WY      Port Jason  624 Faulkner Orchard
B+                   250    WY      Reneeshire      717 Patel Square

Category               Culture Services
SubCategory        Restaurants   Police Schools
(Culture, Museums)
A-                          C-       A+       C
C-                           D        D      B+
D-                          D-        D       D
A                           D-       A-      A-
F                            A       C+      B+
...                        ...      ...     ...
D-                           B        B       D
A+                           C       A-       C
D                           C-       A-      B-
F                           A-       C+      C+
B+                           B        D       A

[251 rows x 7 columns]